const {chromium}=require('../storage/browser-tools/node_modules/playwright-core');
const {loadImage,createCanvas}=require('../storage/browser-tools/node_modules/@napi-rs/canvas');
const decode=require('../storage/browser-tools/jsQR');
const fs=require('fs');
const assert=require('assert/strict');
async function readQR(bytes){const img=await loadImage(bytes),canvas=createCanvas(img.width,img.height),ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);return decode(ctx.getImageData(0,0,img.width,img.height).data,img.width,img.height)?.data;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
const context=await browser.newContext({viewport:{width:1400,height:1000},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Content Security Policy'))errors.push(m.text());});
const base='http://127.0.0.1:8086';await page.goto(base+'/');
assert.equal(await page.locator('.home-page main > section').first().getAttribute('id'),'free-qr-generator');await page.screenshot({path:'storage/home-updated-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth+1),false);await page.screenshot({path:'storage/home-updated-mobile.png',fullPage:true});await page.setViewportSize({width:1400,height:1000});const samples={url:[{url:'https://example.com/?x=1&y=2'},'https://example.com/?x=1&y=2'],text:[{text:'Hello नमस्ते 😀'},'Hello नमस्ते 😀'],phone:[{phone:'+919876543210'},'tel:+919876543210'],email:[{email:'hello@example.com',subject:'Hello & welcome',message:'Hi there'},'mailto:hello%40example.com?subject=Hello%20%26%20welcome&body=Hi%20there'],whatsapp:[{phone:'+919876543210',message:'Hello'},'https://wa.me/919876543210?text=Hello'],sms:[{phone:'+919876543210',message:'Hi'},'smsto:+919876543210:Hi'],wifi:[{ssid:'Cafe; WiFi',password:'a:b;c'},'WIFI:T:WPA;S:Cafe\\; WiFi;P:a\\:b\\;c;H:false;;'],vcard:[{first:'Jane',last:'Doe',email:'jane@example.com'},'BEGIN:VCARD'],location:[{location:'Pune, India'},'https://www.google.com/maps/search/?api=1&query=Pune%2C%20India'],event:[{title:'Opening day',start:'2026-10-01T10:00',end:'2026-10-01T12:00'},'BEGIN:VCALENDAR'],upi:[{address:'shop@bank',name:'My Shop',amount:'12.50'},'upi://pay?pa=shop%40bank&pn=My+Shop&cu=INR&am=12.50'],crypto:[{wallet:'bitcoin:bc1qexample'},'bitcoin:bc1qexample'],file:[{url:'https://example.com/menu.pdf'},'https://example.com/menu.pdf'],social:[{url:'https://instagram.com/example'},'https://instagram.com/example'],review:[{url:'https://g.page/r/example/review'},'https://g.page/r/example/review'],business:[{name:'Local shop',description:'Coffee; tea, snacks\nFresh daily',address:'Pune, India',phone:'+919876543210',email:'shop@example.com',url:'https://example.com',hours:'Mon-Sat 9am-6pm'},'BEGIN:VCARD']};
for(const [type,[values,expected]] of Object.entries(samples)){await page.locator('#qr-type').selectOption(type);for(const [key,value]of Object.entries(values))await page.locator('#qr-fields [name='+key+']').fill(value);await page.locator('#qr-form [type=submit]').click();await page.locator('#qr-preview svg').waitFor();const wait=page.waitForEvent('download');await page.locator('[data-qr-export=png]').click();const file=await wait;const decoded=await readQR(fs.readFileSync(await file.path()));assert.ok(decoded?.startsWith(expected),type+' failed decoding: '+decoded);if(type==='business'){for(const field of ['FN:Local shop','ORG:Local shop','TEL;TYPE=WORK,VOICE:+919876543210','EMAIL;TYPE=WORK:shop@example.com','ADR;TYPE=WORK:;;Pune\\, India;;;;','URL:https://example.com','NOTE:Coffee\\; tea\\, snacks\\nFresh daily\\nOpening hours: Mon-Sat 9am-6pm','END:VCARD'])assert.ok(decoded.includes(field),'Missing '+field);assert.ok(await page.locator('#qr-business-details').isVisible());assert.ok((await page.locator('#qr-business-details').innerText()).includes('Mon-Sat 9am-6pm'));}}
await page.locator('#qr-type').selectOption('url');await page.locator('#qr-fields [name=url]').fill('https://example.com');await page.locator('#qr-form [name=style]').selectOption('rounded');
const logo=createCanvas(60,60),ctx=logo.getContext('2d');ctx.fillStyle='#f07020';ctx.fillRect(0,0,60,60);await page.locator('[name=logo]').setInputFiles({name:'logo.png',mimeType:'image/png',buffer:logo.toBuffer('image/png')});await page.waitForFunction(()=>document.querySelector('#qr-status').textContent.includes('Logo ready'));await page.locator('#qr-form [type=submit]').click();
for(const format of ['png','svg']){const wait=page.waitForEvent('download');await page.locator('[data-qr-export='+format+']').click();const file=await wait;assert.equal(await readQR(fs.readFileSync(await file.path())),'https://example.com',format+' styled logo decode');}
await page.locator('[data-qr-export=copy]').click();await page.waitForFunction(()=>document.querySelector('#qr-status').textContent==='QR image copied.');assert.ok(await page.evaluate(async()=> (await navigator.clipboard.read())[0].types.includes('image/png')));
await page.evaluate(()=>{window.print=()=>{window.printCalled=document.body.classList.contains('qr-printing')&&!!document.querySelector('#qr-print-sheet svg');window.dispatchEvent(new Event('afterprint'));};});await page.locator('[data-qr-export=print]').click();assert.equal(await page.evaluate(()=>window.printCalled),true);
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.body.scrollWidth>innerWidth+1),false);await page.locator('#free-qr-generator').screenshot({path:'storage/qr-mobile.png'});
await page.locator('[name=foreground]').fill('#ffffff');await page.locator('#qr-form [type=submit]').click();assert.ok((await page.locator('#qr-status').textContent()).includes('contrast'));assert.equal(await page.locator('#qr-actions').isVisible(),false);
await page.goto(base+'/seo-tools');assert.equal(await page.locator('#qr-form').count(),1);
assert.deepEqual(errors,[]);console.log('PASS: all 16 QR types, business fields, exports, clipboard, print, validation and responsive layout');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});