const {chromium}=require('../storage/browser-tools/node_modules/playwright-core'),assert=require('assert/strict'),fs=require('fs');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),home=await context.newPage(),errors=[];home.on('pageerror',e=>errors.push(e.message));
  await home.goto('http://127.0.0.1:8086/');const demo=home.locator('[data-chat-widget="demo"]');await demo.locator('.bubble').first().waitFor();assert.equal(await home.evaluate(()=>scrollY),0,'Demo does not steal focus or scroll on load');await demo.locator('.composer input').fill('Tell me about SEO');await demo.locator('.composer button').click();await demo.getByText('Our SEO service includes', {exact:false}).waitFor();await home.locator('#live-chat-demo').screenshot({path:'storage/chat-home-demo.png'});
  const customer=await browser.newContext({viewport:{width:390,height:844}}),page=await customer.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8091');const host=page.locator('[data-chat-widget]');await host.locator('.launcher').click();await host.locator('.bubble').first().waitFor();assert.ok((await host.locator('.messages').textContent()).includes('SEO audits'));assert.notEqual(await host.locator('.composer button').evaluate(b=>getComputedStyle(b).backgroundColor),'rgb(255, 0, 0)');
  await host.locator('.composer input').fill('What does SEO cost?');await host.locator('.composer button').click();await host.getByText('An SEO audit costs 200 units.',{exact:true}).waitFor();await page.screenshot({path:'storage/chat-customer-mobile.png',fullPage:true});
  await host.locator('.contact').click();for(const [key,value]of Object.entries({name:'Browser Chat Visitor',phone:'+1 202 555 0133',email:'browser@example.com',service:'SEO quote',message:'Please send a quote'}))await host.locator('[name='+key+']').fill(value);await host.locator('[name=consent]').check();await host.locator('.lead-form button[type=submit]').click();await host.getByText('Your request was saved. Thank you.',{exact:true}).waitFor();assert.ok(await host.locator('.contact').isHidden());
  await page.reload();await host.locator('.launcher').click();await host.getByText('Your details have been sent',{exact:false}).waitFor();assert.ok(await host.locator('.contact').isHidden());
  const owner=await browser.newContext({viewport:{width:1440,height:1000}}),dashboard=await owner.newPage();dashboard.on('pageerror',e=>errors.push(e.message));const creds=JSON.parse(fs.readFileSync('storage/test-chat-credentials.json')).owner;await dashboard.goto('http://127.0.0.1:8086/login');await dashboard.locator('[name=email]').fill(creds.email);await dashboard.locator('[name=password]').fill(creds.password);await Promise.all([dashboard.waitForURL('**/dashboard'),dashboard.locator('form button').click()]);
  const widget=JSON.parse(fs.readFileSync('storage/test-chat-widget.json'));await dashboard.goto('http://127.0.0.1:8086/live-chat?tab=leads&widget='+widget.id);await dashboard.getByRole('row').filter({hasText:'Browser Chat Visitor'}).first().getByRole('link',{name:'Open lead'}).click();await dashboard.getByRole('link',{name:'View full conversation'}).click();await dashboard.locator('[data-api="chat/reply"] [name=message]').fill('Hello from your team. We can help with your SEO request.');await dashboard.locator('[data-api="chat/reply"] button').click();await host.getByText('Hello from your team. We can help with your SEO request.',{exact:true}).waitFor({timeout:20000});
  await dashboard.goto('http://127.0.0.1:8086/live-chat?tab=analytics&widget='+widget.id);await dashboard.screenshot({path:'storage/chat-analytics-desktop.png',fullPage:true});await dashboard.setViewportSize({width:390,height:844});await dashboard.goto('http://127.0.0.1:8086/live-chat?widget='+widget.id);assert.ok(await dashboard.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await dashboard.screenshot({path:'storage/chat-settings-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS animated Home demo, cross-origin embed, CSS isolation, knowledge reply, consent and lead submission, session resume, live human reply, mobile dashboard and analytics.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
