const assert=require('assert/strict'),fs=require('fs');
const base=process.env.TEST_BASE||'http://127.0.0.1:8086',credentials=JSON.parse(fs.readFileSync('storage/test-chat-credentials.json'));
function client(){let cookie='',csrf='';return {async get(path){const r=await fetch(base+path,{headers:{Cookie:cookie},redirect:'manual'});const next=r.headers.getSetCookie();if(next.length)cookie=next.map(c=>c.split(';')[0]).join('; ');const body=await r.text();csrf=body.match(/name="csrf-token" content="([^"]+)"/)?.[1]||csrf;return {status:r.status,body};},async post(path,data){const r=await fetch(base+path,{method:'POST',headers:{Cookie:cookie},body:new URLSearchParams({csrf,...data}),redirect:'manual'});const next=r.headers.getSetCookie();if(next.length)cookie=next.map(c=>c.split(';')[0]).join('; ');const body=await r.text();let json;try{json=JSON.parse(body);}catch{}return {status:r.status,body,json};}};}
(async()=>{
 const owner=client(),other=client();for(const [c,key]of[[owner,'owner'],[other,'other']]){await c.get('/login');assert.equal((await c.post('/login',credentials[key])).status,303);assert.equal((await c.get('/live-chat')).status,200);}
 const fields={name:'Chat Test Business',business_info:'We provide SEO audits and website design.',allowed_origins:'http://127.0.0.1:8091',color:'#18634f',position:'right',size:'standard',button_style:'pill',avatar:'SEO',welcome:'Hello there!',placeholder:'Ask a question',offline:'Our team will follow up.',online:'1',mobile:'1',desktop:'1',branding:'1',notify:'1',enabled:'1',field_name:'required',field_phone:'required',field_email:'required',field_service:'required',field_message:'optional'};
 const created=await owner.post('/api/v1/chat/widget',fields);assert.equal(created.status,200,created.body);assert.ok(created.json.data.redirect.startsWith(new URL(base).pathname.replace(/\/$/,'')+'/live-chat'),'Redirect preserves app base path');const wid=new URL(created.json.data.redirect,base).searchParams.get('widget');const embed=await owner.get('/live-chat?tab=embed&widget='+wid);const publicId=embed.body.match(/data-widget="([a-f0-9]{32})"/)?.[1];assert.ok(publicId);
 assert.equal((await other.get('/live-chat?widget='+wid)).status,404);assert.equal((await other.post('/api/v1/chat/widget',{...fields,id:wid})).status,404);
 assert.equal((await owner.post('/api/v1/chat/knowledge',{widget_id:wid,question:'What does SEO cost?',keywords:'price pricing cost',answer:'An SEO audit costs 200 units.'})).status,200);
 assert.equal((await owner.post('/api/v1/chat/automation',{widget_id:wid,name:'High intent SEO',keyword:'SEO',min_score:'70',target_status:'Qualified',enabled:'1'})).status,200);
 const knowledgePage=await owner.get('/live-chat?tab=knowledge&widget='+wid);const kid=knowledgePage.body.match(/&edit=(\d+)/)?.[1];assert.ok(kid);assert.equal((await owner.post('/api/v1/chat/knowledge',{widget_id:wid,id:kid,question:'What does SEO cost?',keywords:'price pricing cost',answer:'An SEO audit costs 200 units.'})).status,200);
 const automationPage=await owner.get('/live-chat?tab=automation&widget='+wid);const ruleId=automationPage.body.match(/&edit=(\d+)/)?.[1];assert.ok(ruleId);assert.equal((await owner.post('/api/v1/chat/automation',{widget_id:wid,id:ruleId,name:'Qualified SEO requests',keyword:'SEO',min_score:'70',target_status:'Qualified',enabled:'1'})).status,200);
 async function pub(action,data,origin='http://127.0.0.1:8091'){const r=await fetch(base+'/api/chat/'+action+'?widget='+publicId,{method:data?'POST':'GET',headers:{Origin:origin,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});const json=await r.json();return {status:r.status,json,origin:r.headers.get('access-control-allow-origin')};}
 const config=await pub('config');assert.equal(config.status,200);assert.equal(config.origin,'http://127.0.0.1:8091');assert.equal((await pub('config',null,'https://attacker.example')).status,403);
 const started=await pub('start',{});assert.equal(started.status,200,JSON.stringify(started));const token=started.json.data.token;assert.ok(started.json.data.messages[0].body.includes('SEO audits'));
 const message={token,message:'What is your SEO pricing?',client_id:'chat-test-message-001'};const reply=await pub('message',message);assert.equal(reply.status,200,JSON.stringify(reply));assert.ok(reply.json.data.messages.some(m=>m.body==='An SEO audit costs 200 units.'));const repeated=await pub('message',message);assert.equal(repeated.json.data.messages.length,reply.json.data.messages.length);
 assert.equal((await pub('poll',{token:'a'.repeat(64)})).status,401);assert.equal((await pub('poll',{token},new URL(base).origin)).status,401);
 const lead={token,name:'Test Visitor',phone:'+1 202 555 0100',email:'visitor@example.com',service:'SEO quote',message:'Please contact me',consent:true};assert.equal((await pub('lead',{...lead,consent:false})).status,422);const captured=await pub('lead',lead);assert.equal(captured.status,200,JSON.stringify(captured));assert.ok(captured.json.data.lead_captured);assert.equal((await pub('lead',lead)).json.data.messages.length,captured.json.data.messages.length);
 const leads=await owner.get('/live-chat?tab=leads&widget='+wid);assert.ok(leads.body.includes('Test Visitor'));assert.ok(leads.body.includes('Qualified'));const lid=leads.body.match(/tab=lead[^" ]*&id=(\d+)/)?.[1];assert.ok(lid);
 const detail=await owner.get('/live-chat?tab=lead&id='+lid);assert.equal(detail.status,200);const cid=detail.body.match(/tab=conversations&id=(\d+)/)?.[1];assert.ok(cid);assert.equal((await other.get('/live-chat?tab=lead&id='+lid)).status,404);assert.equal((await other.post('/api/v1/chat/lead',{id:lid,status:'Converted'})).status,404);
 assert.equal((await owner.post('/api/v1/chat/reply',{id:cid,message:'A real team member is here.'})).status,200);const polled=await pub('poll',{token});assert.equal(polled.json.data.mode,'human');assert.ok(polled.json.data.messages.some(m=>m.role==='agent'));
 assert.equal((await owner.post('/api/v1/chat/lead',{id:lid,status:'Converted',notes:'Test conversion'})).status,200);
 for(const tab of ['knowledge','conversations','leads','score','automation','notifications','analytics','embed'])assert.equal((await owner.get('/live-chat?tab='+tab+'&widget='+wid)).status,200,tab);
 assert.equal((await owner.post('/api/v1/chat/widget',{...fields,id:wid,enabled:'0'})).status,200);assert.equal((await pub('poll',{token})).status,404);await owner.post('/api/v1/chat/widget',{...fields,id:wid});
 fs.writeFileSync('storage/test-chat-widget.json',JSON.stringify({id:wid,public_id:publicId}));console.log('PASS widget create/edit, owner isolation, CORS, knowledge, idempotent messages/leads, consent, score automation, notifications, human replies, status, dashboard pages, embed and disable.');
})().catch(e=>{console.error(e);process.exit(1);});
