<?php
require dirname(__DIR__).'/includes/bootstrap.php';require ROOT.'/includes/auth.php';
if(PHP_SAPI!=='cli'||!str_starts_with(cfg('DB_NAME'),'seo_autopilot_test'))throw new RuntimeException('This suite requires an isolated test database.');
$n=0;function verify(bool $ok,string $name):void{global $n;if(!$ok)throw new RuntimeException('FAIL '.$name);$n++;echo 'PASS '.$name."\n";}
$w=row('SELECT * FROM websites ORDER BY id LIMIT 1');$job=row('SELECT * FROM crawl_jobs WHERE website_id=? ORDER BY id DESC LIMIT 1',[$w['id']]);verify($job['status']==='completed','Real public crawl completed');verify((int)value('SELECT COUNT(*) FROM pages WHERE job_id=?',[$job['id']])>0,'Real pages stored');verify((int)value('SELECT COUNT(*) FROM seo_issues WHERE website_id=?',[$w['id']])>0,'Real audit issues stored');
$config['RAZORPAY_WEBHOOK_SECRET']='test-secret-local-only';$raw=json_encode(['event'=>'payment.captured','payload'=>['payment'=>['entity'=>['id'=>'test_payment_'.bin2hex(random_bytes(4)),'order_id'=>'test_order_'.bin2hex(random_bytes(4)),'status'=>'captured','amount'=>199900,'currency'=>'INR']]]]);$event=json_decode($raw,true);$entity=$event['payload']['payment']['entity'];
query('INSERT INTO payments(user_id,plan_id,order_id,amount) VALUES (?,?,?,?)',[$w['user_id'],2,$entity['order_id'],199900]);$pid=(int)db()->lastInsertId();$sig=hash_hmac('sha256',$raw,$config['RAZORPAY_WEBHOOK_SECRET']);
try{Payment::webhook($raw,'invalid');verify(false,'Reject invalid webhook');}catch(HttpError $e){verify($e->getCode()===401,'Reject invalid webhook signature');}
$event['payload']['payment']['entity']['amount']=100;$bad=json_encode($event);try{Payment::webhook($bad,hash_hmac('sha256',$bad,$config['RAZORPAY_WEBHOOK_SECRET']));verify(false,'Reject amount mismatch');}catch(HttpError){verify(value('SELECT status FROM payments WHERE id=?',[$pid])==='pending','Reject mismatched amount without fulfillment');}
Payment::webhook($raw,$sig);verify(value('SELECT status FROM payments WHERE id=?',[$pid])==='paid','Signed captured payment fulfilled');$subscriptions=(int)value('SELECT COUNT(*) FROM subscriptions WHERE user_id=?',[$w['user_id']]);Payment::webhook($raw,$sig);verify((int)value('SELECT COUNT(*) FROM subscriptions WHERE user_id=?',[$w['user_id']])===$subscriptions,'Duplicate webhook is idempotent');verify((int)value('SELECT COUNT(*) FROM invoices WHERE payment_id=?',[$pid])===1,'One invoice per payment');
query('DELETE FROM invoices WHERE payment_id=?',[$pid]);query('DELETE FROM payments WHERE id=?',[$pid]);query("DELETE FROM subscriptions WHERE user_id=? AND plan_id=2",[$w['user_id']]);
email_queue('error-test@example.test','SMTP error path','Test body');Mailer::work();verify(value("SELECT status FROM email_logs WHERE recipient='error-test@example.test' ORDER BY id DESC LIMIT 1")==='failed','SMTP missing configuration handled');
verify(!str_contains(Report::html(['title'=>'<script>alert(1)</script>','created_at'=>date('c'),'snapshot'=>json_encode(['website'=>$w,'audit'=>null,'issues'=>[],'keywords'=>[],'backlinks'=>[],'competitors'=>[],'tasks'=>[],'branding'=>[]])]),'<script>'),'Report output escapes HTML');
file_put_contents(ROOT.'/storage/deep-test-results.txt',"$n deep checks passed at ".date(DATE_ATOM));echo "PASS: $n deep checks\n";
