// Start Chrome with --remote-debugging-port=9225 and a disposable profile before running.
const tabs=await(await fetch('http://127.0.0.1:9225/json')).json();const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}});const send=(method,params={})=>new Promise((resolve,reject)=>{const requestId=++id;const timer=setTimeout(()=>reject(Error('Browser request timed out: '+method)),15000);pending.set(requestId,m=>{clearTimeout(timer);m.error?reject(Error(m.error.message)):resolve(m.result);});ws.send(JSON.stringify({id:requestId,method,params}));});
try{
 await send('Network.clearBrowserCookies');await send('Page.navigate',{url:process.env.DEMO_TEST_URL||'http://localhost/ppso/'});await new Promise(r=>setTimeout(r,1400));
 const result=await send('Runtime.evaluate',{awaitPromise:true,returnByValue:true,expression:`(async()=>{
 const checks=[];const check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};const wait=()=>new Promise(r=>setTimeout(r,650));
 const qr=document.getElementById('qr-form');qr.elements.url.value='https://seozentro.com';for(let i=0;i<4;i++){qr.requestSubmit();await wait();check(i<3?!!document.querySelector('#qr-preview svg'):document.getElementById('qr-status').textContent.includes('3 free tries'),'QR attempt '+(i+1));}
 const wa=document.getElementById('whatsapp-form');wa.elements.phone.value='+91 8368487667';wa.elements.message.value='Hello & welcome';for(let i=0;i<4;i++){wa.requestSubmit();await wait();check(i<3?document.getElementById('whatsapp-output').value==='https://wa.me/918368487667?text=Hello%20%26%20welcome':document.getElementById('whatsapp-result').hidden&&document.getElementById('whatsapp-status').textContent.includes('3 free tries'),'WhatsApp attempt '+(i+1));}
 const chat=document.querySelector('[data-chat-widget="demo"]').shadowRoot;for(let i=0;i<4;i++){chat.querySelector('.composer input').value='SEO services';chat.querySelector('.composer').requestSubmit();await wait();check(i<3?chat.querySelectorAll('.bubble.visitor').length===i+1:chat.querySelector('.status').textContent.includes('3 free tries'),'Chat attempt '+(i+1));}
 document.querySelector('[data-expert-open="hire"]').click();check(document.getElementById('expert-enquiry').open,'Hire expert dialog opens');document.querySelector('[data-expert-close]').click();
 return checks;
 })()`});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);console.log(result.result.value);
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:900,deviceScaleFactor:1,mobile:true});const layout=await send('Runtime.evaluate',{returnByValue:true,expression:'({viewport:innerWidth,width:document.documentElement.scrollWidth})'});console.log(layout.result.value);if(layout.result.value.width>390)throw Error('Mobile overflow');
 console.log('PASS 13 demo interactions and mobile layout');
}finally{await send('Browser.close');ws.close();}
