<?php
require dirname(__DIR__).'/includes/bootstrap.php';
if(!str_starts_with(cfg('DB_NAME'),'seo_autopilot_test'))throw new RuntimeException('This suite requires an isolated test database.');
$base=cfg('APP_URL');$credentials=json_decode(file_get_contents(getenv('SEO_TEST_CREDENTIALS') ?: ROOT.'/storage/test-credentials.json'),true);$checks=0;$cookie=ROOT.'/storage/test-cookie.txt';
function http(string $path,?array $post=null,?string $jar=null): array {global $base,$cookie;$c=curl_init($base.$path);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$jar??$cookie,CURLOPT_COOKIEFILE=>$jar??$cookie,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_TIMEOUT=>30,CURLOPT_PROXY=>'']);if($post!==null)curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$post]);$raw=curl_exec($c);if($raw===false)throw new RuntimeException(curl_error($c));$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);curl_close($c);return ['status'=>$status,'headers'=>substr($raw,0,$size),'body'=>substr($raw,$size)];}
function token(array $response): string {preg_match('/(?:name="csrf" value|name="csrf-token" content)="([a-f0-9]+)"/',$response['body'],$m);return $m[1]??'';}
function test(bool $ok,string $name): void {global $checks;if(!$ok)throw new RuntimeException('FAIL '.$name);echo 'PASS '.$name."\n";$checks++;}
function api_test(string $action,array $data,int $expected=200): array {global $csrf;$r=http('/api/v1/'.$action,['csrf'=>$csrf]+$data);test($r['status']===$expected,$action.' HTTP '.$expected.($r['status']!==$expected?' got '.$r['status'].' '.strip_tags($r['body']):''));return json_decode($r['body'],true)??[];}
$home=http('/');test($home['status']===200&&str_contains($home['body'],'Automate your SEO'),'Public homepage');
if(!is_file(ROOT.'/storage/installed.lock')){$r=http('/install');$r=http('/install',['csrf'=>token($r),'install_token'=>cfg('INSTALL_TOKEN'),'db_host'=>cfg('DB_HOST'),'db_port'=>cfg('DB_PORT'),'db_name'=>cfg('DB_NAME'),'db_user'=>cfg('DB_USER'),'db_pass'=>cfg('DB_PASS'),'app_url'=>$base,'admin_name'=>'Test Administrator','admin_email'=>$credentials['email'],'admin_password'=>$credentials['password']]);test($r['status']===303,'Installer creates schema and admin');}
test((int)value('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=?',[cfg('DB_NAME')])===48,'Database schema installed');
test(http('/install')['status']===403,'Installer locks after installation');
$r=http('/login');$r=http('/login',['csrf'=>token($r),'email'=>$credentials['email'],'password'=>$credentials['password']]);test($r['status']===303,'Administrator login');$dashboard=http('/dashboard');$csrf=token($dashboard);test($dashboard['status']===200&&$csrf!=='','Authenticated dashboard');
foreach(['/admin','/admin/users','/admin/plans','/admin/settings','/admin/logs','/billing','/profile','/websites'] as $path)test(http($path)['status']===200,'Page '.$path);
$r=http('/api/v1/website',['name'=>'Forged','domain'=>'https://example.com']);test($r['status']===419,'CSRF rejection');
$site=api_test('website',['name'=>'Example website','domain'=>'https://example.com','country'=>'India','language'=>'en','search_engine'=>'google','timezone'=>'UTC']);$wid=(int)value('SELECT id FROM websites WHERE user_id=(SELECT id FROM users WHERE email=?) ORDER BY id DESC LIMIT 1',[$credentials['email']]);test($wid>0,'Website stored');
api_test('website',['name'=>'Private','domain'=>'http://127.0.0.1','timezone'=>'UTC'],422);
api_test('save',['website_id'=>$wid,'module'=>'keywords','keyword'=>'seo platform','country'=>'India','language'=>'en','search_engine'=>'google','device'=>'desktop']);
api_test('save',['website_id'=>$wid,'module'=>'tasks','title'=>'Review title tags','priority'=>'high','status'=>'open']);
api_test('save',['website_id'=>$wid,'module'=>'competitors','domain'=>'https://example.org','notes'=>'Research target']);
api_test('save',['website_id'=>$wid,'module'=>'backlinks','source_url'=>'https://example.org/article','target_url'=>'https://example.com/','anchor'=>'Example','follow'=>'follow','status'=>'active']);
api_test('save',['website_id'=>$wid,'module'=>'content','topic'=>'SEO basics','keyword'=>'seo','audience'=>'Business owners']);
api_test('save',['website_id'=>$wid,'module'=>'human-services','service'=>'Technical SEO','budget'=>'5000','description'=>'Review the latest audit.','priority'=>'medium']);
api_test('ai',['website_id'=>$wid,'message'=>'What should I fix?'],503);
api_test('checkout',['plan_id'=>2],503);
api_test('schema',['website_id'=>$wid,'type'=>'Organization','json'=>'{"name":"Example"}']);
$report=api_test('report',['website_id'=>$wid]);$rid=(int)value('SELECT id FROM reports WHERE website_id=? ORDER BY id DESC LIMIT 1',[$wid]);test(http('/report?id='.$rid.'&website_id='.$wid)['status']===200,'Report view');$pdf=http('/report?id='.$rid.'&website_id='.$wid.'&pdf=1');test($pdf['status']===200&&str_starts_with($pdf['body'],'%PDF'),'PDF download');
foreach(['dashboard','audit','pages','keywords','rankings','research','competitors','backlinks','content','tasks','reports','ai-assistant','schema','internal-links','automations','human-services','team'] as $path)test(http('/'.$path.'?website_id='.$wid)['status']===200,'Project page '.$path);
$r=http('/api/v1/export?module=keywords&website_id='.$wid);test($r['status']===200&&str_contains($r['body'],'seo platform'),'CSV export');
test(http('/missing-page')['status']===404,'404 response');test(http('/config/local.php')['status']===403,'Protected config route');test(http('/database/database.sql')['status']===403,'Protected schema route');
$r=http('/logout',['csrf'=>$csrf]);test($r['status']===303,'Logout');test(http('/dashboard')['status']===303,'Logged-out dashboard redirects');
$customerEmail='customer-'.bin2hex(random_bytes(3)).'@example.test';$password=bin2hex(random_bytes(10));$r=http('/register');$r=http('/register',['csrf'=>token($r),'name'=>'Test Customer','email'=>$customerEmail,'password'=>$password]);test($r['status']===303,'Customer registration');$csrf=token(http('/dashboard'));test(http('/admin')['status']===403,'Customer denied admin');api_test('save',['website_id'=>$wid,'module'=>'tasks','title'=>'IDOR probe'],403);
$r=http('/logout',['csrf'=>$csrf]);$r=http('/forgot-password');$r=http('/forgot-password',['csrf'=>token($r),'email'=>$customerEmail]);test($r['status']===303,'Password reset request');$body=value('SELECT body FROM email_logs WHERE recipient=? AND subject=? ORDER BY id DESC LIMIT 1',[$customerEmail,'Reset your password']);parse_str(parse_url($body,PHP_URL_QUERY),$parts);$r=http('/reset-password?token='.$parts['token']);$newPassword=bin2hex(random_bytes(10));$r=http('/reset-password',['csrf'=>token($r),'token'=>$parts['token'],'password'=>$newPassword]);test($r['status']===303,'Password reset consumes token');$r=http('/login');$r=http('/login',['csrf'=>token($r),'email'=>$customerEmail,'password'=>$newPassword]);test($r['status']===303,'Login with reset password');
file_put_contents(ROOT.'/storage/http-test-results.txt',"$checks HTTP/database checks passed at ".date(DATE_ATOM));echo "PASS: $checks HTTP/database checks\n";

