<?php
require __DIR__.'/unit.php';
$url='https://www.instagram.com/p/AbC_123-/';$image='https://scontent.cdninstagram.com/photo.jpg?a=1&b=2';$video='https://video.xx.fbcdn.net/video.mp4';
check(InstagramDownloader::normalize(' https://instagram.com/p/AbC_123-/?igsh=abc#x ')===$url,'Normalize Instagram link and remove tracking parameters');
foreach(['http://instagram.com/p/abc/','https://instagram.com.evil.test/p/abc/','https://evil.test/?url=instagram.com/p/abc/','https://instagram.com@evil.test/p/abc/','https://user@instagram.com/p/abc/','https://instagram.com:443/p/abc/','https://instagram.com/stories/name/123/','https://instagram.com/name/','https://instagram.com/accounts/login/','https://instagram.com/p/abc/embed/','https://instagram.com/p/../','https://instagram.com/p/%61bc/','https://127.0.0.1/p/abc/','https://instagram.com\\@evil.test/p/abc/'] as $bad)rejects(fn()=>InstagramDownloader::normalize($bad),'Reject unsupported URL '.$bad);
foreach(['https://127.0.0.1/a','https://cdninstagram.com.evil.test/a','http://scontent.cdninstagram.com/a','https://scontent.cdninstagram.com@evil.test/a','https://scontent.cdninstagram.com:8443/a','file:///etc/passwd','data:image/svg+xml,test','https://www.instagram.com/accounts/login/'] as $bad)rejects(fn()=>InstagramDownloader::mediaUrl($bad),'Reject unsafe media host '.$bad);
check(InstagramDownloader::mediaUrl($image)===$image,'Preserve signed CDN URL');
check(!InstagramDownloader::pageAllowed('https://www.instagram.com/accounts/login/',$url),'Do not follow login redirects');
check(!InstagramDownloader::pageAllowed('https://www.instagram.com/p/other/',$url),'Do not follow redirects to another post');
$html='<html><head><meta property="og:title" content="A &amp; B"><meta property="og:url" content="'.$url.'"><meta property="og:image" content="'.htmlspecialchars($image).'"></head></html>';
$result=InstagramDownloader::parse($html,$url);check($result['media']===$image&&$result['type']==='image','Extract and decode public image metadata');check($result['title']==='A & B','Decode title');
$result=InstagramDownloader::parse(str_replace('</head>','<meta property="og:video:secure_url" content="'.$video.'"></head>',$html),$url);check($result['type']==='video'&&$result['media']===$video&&$result['thumbnail']===$image,'Prefer video with image thumbnail');
$reel=InstagramDownloader::parse('<head><meta property="og:image:url" content="'.$image.'"></head>','https://www.instagram.com/reel/abc/');check($reel['type']==='video'&&!$reel['downloadable']&&$reel['media']===null&&$reel['thumbnail']===$image,'Reel with only image has no downloadable media');
$reelVideo=InstagramDownloader::parse('<head><meta property="og:image" content="'.$image.'"><meta property="og:video" content="'.$video.'"></head>','https://www.instagram.com/reel/abc/');check($reelVideo['content_kind']==='reel'&&$reelVideo['downloadable']&&$reelVideo['media']===$video,'Reel downloads video rather than thumbnail');
$videoPost=InstagramDownloader::parse('<head><meta property="og:type" content="video.other"><meta property="og:image" content="'.$image.'"></head>',$url);check(!$videoPost['downloadable']&&$videoPost['media']===null,'Video post without video does not download its thumbnail');
check(InstagramDownloader::parse($html,$url)['downloadable'],'Image post remains downloadable');
foreach(['<head><title>Login • Instagram</title><meta property="og:image" content="'.$image.'"></head>','<head><meta property="og:image" content="'.$image.'"></head><body><input type="password"></body>','<head><meta property="og:image" content="'.$image.'"></head><script>{"is_private":true}</script>','<head><meta property="og:url" content="https://www.instagram.com/"><meta property="og:image" content="'.$image.'"></head>','<head><title>CAPTCHA</title></head>','<html><body>Try again</body></html>','<head><meta property="og:image" content="http://127.0.0.1/secret"></head>'] as $blocked)rejects(fn()=>InstagramDownloader::parse($blocked,$url),'Reject blocked, private, generic or missing-media page');
foreach([401,403,404,410,429,500] as $status)rejects(fn()=>InstagramDownloader::extract($url,fn()=>['status'=>$status]),'Handle Instagram HTTP '.$status);
rejects(fn()=>InstagramDownloader::extract($url,fn()=>throw new RuntimeException('Network failure')),'Handle timeout without leaking network details');
$result=InstagramDownloader::extract($url,fn()=>['status'=>200,'url'=>$url,'headers'=>['content-type'=>'text/html; charset=utf-8'],'body'=>$html]);check($result['type']==='image','Public page extraction success');
rejects(fn()=>InstagramDownloader::parse('<head><meta property="og:image" content="'.$image.'"></head><body><h2>This Account is Private</h2></body>',$url),'Reject private-account heading');
rejects(fn()=>InstagramDownloader::parse('<head><meta property="og:image" content="'.$image.'"></head><body><form action="/challenge/"></form></body>',$url),'Reject challenge form despite metadata');
$png=base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2n9sAAAAASUVORK5CYII=');
check(InstagramDownloader::fileFormat($png,'image')['extension']==='png','Download detects real PNG bytes');
rejects(fn()=>InstagramDownloader::fileFormat($png,'video'),'Reject image masquerading as video');
rejects(fn()=>InstagramDownloader::fileFormat('<html>Login</html>','image'),'Reject HTML masquerading as image');
rejects(fn()=>InstagramDownloader::fileFormat('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>','image'),'Reject active SVG media');
check(InstagramDownloader::normalize('https://www.instagram.com/author.name/p/AbC_123-/')===$url,'Accept author-qualified public post URL');
check(InstagramDownloader::pageAllowed('https://www.instagram.com/author.name/p/AbC_123-/',$url),'Accept author-qualified canonical metadata');
check(InstagramDownloader::pageAllowed('https://www.instagram.com/author.name/reel/AbC_123-/',$url),'Match reel and post aliases by exact shortcode');
check(!InstagramDownloader::pageAllowed('https://www.instagram.com/author.name/p/different/',$url),'Reject another shortcode in author-qualified metadata');
check(!InstagramDownloader::pageAllowed('https://evil.test/author.name/p/AbC_123-/',$url),'Reject foreign host even with same shortcode');
$canonicalHtml=str_replace('content="'.$url.'"','content="https://www.instagram.com/author.name/p/AbC_123-/"',$html);
check(InstagramDownloader::parse($canonicalHtml,$url)['media']===$image,'Extract media when Instagram canonical URL includes author');
echo "PASS: $total checks\n";
