<?php
require __DIR__.'/unit.php';
$keyword=['id'=>123,'keyword'=>'Coffee','country'=>'India','language'=>'en','device'=>'mobile','domain'=>'https://example.com/','target_url'=>'','search_engine'=>'google'];
check(HasDataRankProvider::parameters($keyword)===['q'=>'Coffee','gl'=>'in','hl'=>'en','deviceType'=>'mobile','num'=>10],'HasData country/language/device mapping');
check(HasDataRankProvider::country('GB')==='gb','Country code input');
rejects(fn()=>HasDataRankProvider::country('Not a country'),'Reject unsupported country without silently changing audience');
rejects(fn()=>HasDataRankProvider::parameters(array_replace($keyword,['search_engine'=>'bing'])),'Reject unsupported search engine');
$data=['requestMetadata'=>['status'=>'ok'],'organicResults'=>[['position'=>1,'link'=>'https://example.com.evil.test/'],['position'=>2,'link'=>'https://notexample.com/'],['position'=>4,'link'=>'https://www.example.com/coffee']]];
check(HasDataRankProvider::parse($data,$keyword)['position']===4,'Match www domain and reject lookalike hosts');
$data['organicResults'][]=['position'=>3,'link'=>'https://shop.example.com/coffee'];
check(HasDataRankProvider::parse($data,$keyword)['position']===3,'Choose best organic position including subdomains');
$keyword['target_url']='https://example.com/coffee/';
check(HasDataRankProvider::parse($data,$keyword)['position']===4,'Exact target page ignores subdomain results');
$keyword['target_url']='https://example.com/missing';
check(HasDataRankProvider::parse($data,array_replace($keyword,['target_url'=>'https://example.com/coffee']),10)['position']===14,'Page-two position includes offset');
check(HasDataRankProvider::parse(['organicResults'=>[['position'=>10,'link'=>'https://example.com/coffee']]],array_replace($keyword,['target_url'=>'https://example.com/coffee']),90)['position']===100,'Position 100 is retained');
check(Ranking::label(null,'hasdata_top100')==='Not found (up to 100)','Missing position explains search depth');
check(Ranking::label(null,null)==='Not checked','Unsearched keyword is distinct from missing result');
check(HasDataRankProvider::parse($data,$keyword)['position']===null,'Missing target returns null rather than fabricated position');
check(HasDataRankProvider::parse(['organicResults'=>[]],$keyword)['position']===null,'Valid empty organic list');
foreach([[],['error'=>'bad'],['organicResults'=>null],['organicResults'=>[['position'=>'1','link'=>'https://example.com']]],['requestMetadata'=>['status'=>'error'],'organicResults'=>[]]] as $bad)rejects(fn()=>HasDataRankProvider::parse($bad,$keyword),'Reject malformed or failed provider payload');
$config['RANKING_API_KEY']='test-key';$calls=[];
$provider=new HasDataRankProvider(function($url)use(&$calls){parse_str(parse_url($url,PHP_URL_QUERY),$params);$start=(int)$params['start'];$calls[]=$start;return ['status'=>200,'body'=>json_encode(['organicResults'=>[['position'=>4,'link'=>$start===20?'https://example.com/missing':'https://other.example/']],'pagination'=>['next'=>'https://www.google.com/search?start='.($start+10)]])];});
check($provider->positions([$keyword])[0]['position']===24,'Provider finds position beyond page one');
check($calls===[0,10,20],'Search stops as soon as target is found');
$calls=[];
$provider=new HasDataRankProvider(function($url)use(&$calls){parse_str(parse_url($url,PHP_URL_QUERY),$params);$calls[]=(int)$params['start'];return ['status'=>200,'body'=>json_encode(['organicResults'=>[['position'=>1,'link'=>'https://other.example/']],'pagination'=>['next'=>'https://www.google.com/search?start=10']])];});
check($provider->positions([$keyword])[0]['position']===null&&count($calls)===10&&end($calls)===90,'Missing target checks at most ten pages');
$calls=0;
$provider=new HasDataRankProvider(function()use(&$calls){$calls++;return ['status'=>200,'body'=>'{"organicResults":[{"position":1,"link":"https://other.example/"}]}'];});
check($provider->positions([$keyword])[0]['position']===null&&$calls===1,'Search stops when Google provides no next page');
$calls=0;
$provider=new HasDataRankProvider(function()use(&$calls){return ++$calls===1?['status'=>200,'body'=>'{"organicResults":[{"position":1,"link":"https://other.example/"}],"pagination":{"next":"https://www.google.com/search?start=10"}}']:['status'=>429,'body'=>'{}'];});
rejects(fn()=>$provider->positions([$keyword]),'Later-page API failure does not return a false missing ranking');
echo "PASS: $total combined unit/ranking checks\n";
