<?php
require dirname(__DIR__).'/includes/bootstrap.php';
if(!str_starts_with(cfg('DB_NAME'),'seo_autopilot_test'))throw new RuntimeException('This suite requires the isolated test database.');
$credentials=json_decode(file_get_contents(getenv('SEO_TEST_CREDENTIALS') ?: ROOT.'/storage/test-credentials.json'),true);$jar=ROOT.'/storage/test-workflow-cookie.txt';$count=0;
function request(string $path,?array $post=null):array{global $jar;$c=curl_init(cfg('APP_URL').$path);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIEFILE=>$jar,CURLOPT_COOKIEJAR=>$jar,CURLOPT_PROXY=>'',CURLOPT_TIMEOUT=>30]);if($post!==null)curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$post]);$body=curl_exec($c);$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);return ['status'=>$status,'body'=>$body];}
function assert_work(bool $ok,string $label):void{global $count;if(!$ok)throw new RuntimeException('FAIL '.$label);$count++;echo "PASS $label\n";}
function form_token(string $path='/dashboard'):string{$r=request($path);preg_match('/name="csrf-token" content="([a-f0-9]+)"/',$r['body'],$m);return $m[1]??'';}
function post_action(string $action,array $data,int $status=200):array{global $csrf;$r=request('/api/v1/'.$action,['csrf'=>$csrf]+$data);assert_work($r['status']===$status,$action.' '.$status.($r['status']!==$status?' got '.$r['status'].' '.$r['body']:''));return json_decode($r['body'],true)??[];}
$csrf=form_token('/login');$r=request('/login',['csrf'=>$csrf,'email'=>$credentials['email'],'password'=>$credentials['password'],'remember'=>'1']);assert_work($r['status']===303,'Login with remember me');$csrf=form_token();$uid=(int)value('SELECT id FROM users WHERE email=?',[$credentials['email']]);$wid=(int)value('SELECT id FROM websites WHERE user_id=? LIMIT 1',[$uid]);
$cookieLines=file($jar);$cookieLines=array_filter($cookieLines,fn($line)=>!str_contains($line,"\tseo_session\t"));file_put_contents($jar,implode('',$cookieLines));assert_work(request('/dashboard')['status']===200,'Remember token restores session');$csrf=form_token();
post_action('website',['domain'=>'https://example.org','name'=>'Quota check','timezone'=>'UTC'],422);
post_action('keyword-bulk',['website_id'=>$wid,'keywords'=>implode("\n",array_map(fn($i)=>'quota '.$i,range(1,60)))],422);
$suffix=bin2hex(random_bytes(3));$csv=ROOT.'/storage/temp/keywords-'.$suffix.'.csv';file_put_contents($csv,"keyword,country,device,search_volume,difficulty,position\nworkflow $suffix,India,mobile,120,35,8\n");post_action('import',['website_id'=>$wid,'module'=>'keywords','csv'=>new CURLFile($csv,'text/csv','keywords.csv')]);assert_work((int)value('SELECT search_volume FROM keywords WHERE keyword=?',['workflow '.$suffix])===120,'CSV stores verified metrics');
$before=(int)value('SELECT COUNT(*) FROM keywords WHERE website_id=?',[$wid]);file_put_contents($csv,"keyword,device\nvalid $suffix,desktop\ninvalid $suffix,tablet\n");post_action('import',['website_id'=>$wid,'module'=>'keywords','csv'=>new CURLFile($csv,'text/csv','keywords.csv')],422);assert_work((int)value('SELECT COUNT(*) FROM keywords WHERE website_id=?',[$wid])===$before,'Invalid CSV rolls back every row');
post_action('keyword-bulk',['website_id'=>$wid,'keywords'=>"bulk alpha $suffix\nbulk beta $suffix"]);
post_action('automation',['website_id'=>$wid,'code'=>'missing_description','enabled'=>'1']);
post_action('project-settings',['website_id'=>$wid,'name'=>'Example website','country'=>'India','language'=>'en','timezone'=>'UTC','search_engine'=>'google','client_name'=>'QA Client','client_email'=>'client@example.test','monthly_report'=>'1']);
$task=(int)value('SELECT id FROM seo_tasks WHERE website_id=? LIMIT 1',[$wid]);post_action('assign-task',['website_id'=>$wid,'id'=>$task,'assigned_user'=>$uid]);post_action('task-status',['website_id'=>$wid,'id'=>$task,'status'=>'completed']);assert_work(value('SELECT status FROM seo_tasks WHERE id=?',[$task])==='completed','Task updates persist');
$competitor=(int)value('SELECT id FROM competitors WHERE website_id=? LIMIT 1',[$wid]);post_action('competitor-keyword',['website_id'=>$wid,'competitor_id'=>$competitor,'keyword'=>'gap '.$suffix,'position'=>'4']);
post_action('research',['website_id'=>$wid,'seed'=>'seo'],503);
post_action('admin/scheduling',['trial_days'=>'7','trial_plan_id'=>'2','grace_days'=>'2','ranking_frequency_hours'=>'24']);
request('/logout',['csrf'=>$csrf]);$csrf=form_token('/register');$email='trial-'.$suffix.'@example.test';$password=bin2hex(random_bytes(10));$r=request('/register',['csrf'=>$csrf,'email'=>$email,'password'=>$password,'name'=>'Trial user']);assert_work($r['status']===303,'Trial account registration');$trialUser=(int)value('SELECT id FROM users WHERE email=?',[$email]);$sub=row('SELECT * FROM subscriptions WHERE user_id=? ORDER BY id DESC LIMIT 1',[$trialUser]);assert_work((int)$sub['is_trial']===1&&(int)$sub['plan_id']===2,'Trial receives configured plan');query('UPDATE subscriptions SET ends_at=DATE_SUB(NOW(),INTERVAL 1 DAY) WHERE id=?',[$sub['id']]);assert_work(plan($trialUser)['slug']==='starter','Grace period retains plan');query('UPDATE subscriptions SET ends_at=DATE_SUB(NOW(),INTERVAL 4 DAY) WHERE id=?',[$sub['id']]);assert_work(plan($trialUser)['slug']==='free','Expired trial returns to Free');
query("UPDATE settings SET value='0' WHERE name IN ('trial_days','grace_days')");
$csrf=form_token();request('/logout',['csrf'=>$csrf]);$csrf=form_token('/login');request('/login',['csrf'=>$csrf,'email'=>$credentials['email'],'password'=>$credentials['password']]);$csrf=form_token();
query("INSERT INTO subscriptions(user_id,plan_id,starts_at,ends_at,is_trial) VALUES (?,4,NOW(),DATE_ADD(NOW(),INTERVAL 1 DAY),1)",[$uid]);$agencySub=(int)db()->lastInsertId();
post_action('invite',['website_id'=>$wid,'email'=>$email]);$inviteBody=value('SELECT body FROM email_logs WHERE recipient=? AND subject LIKE ? ORDER BY id DESC LIMIT 1',[$email,'You are invited%']);assert_work(str_contains($inviteBody,'accept-invitation?token='),'Invitation email queued');
post_action('team',['website_id'=>$wid,'email'=>$email]);post_action('branding',['website_id'=>$wid,'agency_name'=>'QA Agency','agency_website'=>'https://example.com','agency_contact'=>'hello@example.test','report_footer'=>'Prepared for review','brand_color'=>'#ff7a00','logo_url'=>'']);
$result=post_action('report',['website_id'=>$wid]);$report=row('SELECT * FROM reports WHERE website_id=? ORDER BY id DESC LIMIT 1',[$wid]);assert_work(json_decode($report['snapshot'],true)['branding']['agency_name']==='QA Agency','Agency report branding captured');
post_action('email-report',['website_id'=>$wid,'id'=>$report['id']]);
request('/logout',['csrf'=>$csrf]);$csrf=form_token('/login');request('/login',['csrf'=>$csrf,'email'=>$email,'password'=>$password]);assert_work(request('/tasks?website_id='.$wid)['status']===200,'Assigned team project accessible');$csrf=form_token();post_action('project-settings',['website_id'=>$wid,'name'=>'Unauthorized edit'],403);
query('DELETE FROM subscriptions WHERE id=?',[$agencySub]);
file_put_contents(ROOT.'/storage/workflow-test-results.txt',"$count workflow checks passed at ".date(DATE_ATOM));echo "PASS: $count workflow checks\n";
