<?php
$user=require_user();$sites=websites();$wid=(int)($_GET['website_id']??($sites[0]['id']??0));$w=$wid?website($wid):null;
if($section==='website')$section='dashboard';if($section==='subscription')$section='billing';
if($section==='report'){$report=row('SELECT * FROM reports WHERE id=?',[(int)($_GET['id']??0)]);if(!$report)fail('Report not found.',404);$w=website((int)$report['website_id']);$wid=(int)$w['id'];if(isset($_GET['pdf']))Report::pdf($report);}
$defs=Modules::definitions();$title=$defs[$section]['title']??ucwords(str_replace('-',' ',$section));if($section==='dashboard')$title='Overview';if($section==='services')$title='All tools & services';if($section==='local-seo')$title='GBP / Local SEO analyzer';if($section==='ai-assistant')$title='AI writing & assistant';
require ROOT.'/includes/header.php';require ROOT.'/includes/sidebar.php';
?><div class="app-main"><header class="app-topbar"><button class="icon-button mobile-toggle" data-toggle-sidebar aria-controls="sidebar" aria-expanded="false" aria-label="Open navigation">☰</button><div class="breadcrumbs">Workspace &nbsp; / &nbsp; <strong><?=e($title)?></strong></div><div class="top-actions"><span>◎</span><select data-website-picker aria-label="Active website"><option value="0">Select a website</option><?php foreach($sites as $site):?><option value="<?=$site['id']?>" <?=$wid===$site['id']?'selected':''?>><?=e($site['name'])?></option><?php endforeach;?></select><a href="<?=url('/notifications')?>" class="icon-button" aria-label="Notifications">♧ <small><?=(int)value('SELECT COUNT(*) FROM notifications WHERE user_id=? AND read_at IS NULL',[$user['id']])?></small></a><a class="avatar" href="<?=url('/profile')?>"><?=e(mb_substr($user['name'],0,1))?></a></div></header><main class="app-content" id="main"><?php require ROOT.'/includes/alerts.php';?><div class="page-heading"><div><h1><?=$section==='dashboard'?'Your SEO overview.':e($title)?></h1><p><?=e($defs[$section]['description']??($section==='dashboard'?'Track your website health, search rankings, and the next tasks to improve them.':(WorkspaceUI::catalog()[$section][2]??'Everything you need for your next step.')))?></p></div><div class="row"><?php if($w && $section==='dashboard'):?><a class="button secondary" href="<?=url('/reports?website_id='.$wid)?>">↓ Export report</a><button class="button" data-action="crawl" data-website-id="<?=$wid?>">ϟ Run audit</button><?php elseif($section==='websites'):?><a class="button" href="#create">+ Add website</a><?php endif;?></div></div>
<?php
$global=['services','websites','profile','billing','notifications'];
if($w && !in_array($section,$global) && $section!=='report') require ROOT.'/dashboard/website-tabs.php';
if(!$w && !in_array($section,$global)){?><div class="welcome-banner"><div><h3>Your next SEO win starts here.</h3><p>Connect your first website to see its health, issues, and opportunities.</p></div><a href="<?=url('/websites#create')?>" class="button">+ Add website</a></div><?php if($section==='dashboard')require ROOT.'/dashboard/overview.php';else empty_state('Connect a website first','Add a website to start using this tool.');}
elseif(isset($defs[$section])){require ROOT.'/dashboard/tool-guide.php';if($section==='human-services')require ROOT.'/dashboard/service-options.php';require ROOT.'/dashboard/module.php';}
else{require ROOT.'/dashboard/tool-guide.php'; $view=ROOT.'/dashboard/'.$section.'.php'; if(is_file($view))require $view;else require ROOT.'/dashboard/tools.php'; }
if($w && in_array($section,['keywords','competitors','tasks','team','research'])) require ROOT.'/dashboard/supplements.php';
if($w && $section==='backlinks')require ROOT.'/dashboard/backlink-summary.php';
if($w && $section==='pages')require ROOT.'/dashboard/page-suggestions.php';
if($section==='billing'||($w&&$section==='human-services'))require ROOT.'/dashboard/extra-purchases.php';
?></main></div><?php require ROOT.'/includes/footer.php';?>
