<?php
if(!LiveChat::ready()){empty_state('Live chat is being prepared','An administrator can install chat storage from Administration > Tools & services.');return;}
$chatTabs=['widgets'=>'Chat Widgets','knowledge'=>'Business Knowledge','conversations'=>'Conversations','leads'=>'Leads','score'=>'Lead Score','automation'=>'Automation','notifications'=>'Notifications','analytics'=>'Analytics','embed'=>'Embed Code'];
$chatTab=is_string($_GET['tab']??null)?$_GET['tab']:'widgets';if(!isset($chatTabs[$chatTab])&&$chatTab!=='lead')fail('Chat page not found.',404);
$chatWidgets=rows('SELECT * FROM chat_widgets WHERE user_id=? ORDER BY id DESC',[$user['id']]);$chatId=(int)($_GET['widget']??($chatWidgets[0]['id']??0));$chatWidget=$chatId?LiveChat::owned($chatId,(int)$user['id']):null;
$chatLink=fn($tab,$extra='')=>url('/live-chat?tab='.$tab.($chatId?'&widget='.$chatId:'').$extra);
?>
<link rel="stylesheet" href="<?=url('/assets/css/live-chat.css')?>">
<div class="chat-banner"><strong>Every conversation has a next step.</strong><p class="small">Create your widget, add your business knowledge, then paste the embed code into your website. Your existing account and subscription apply; no separate registration is needed.</p></div>
<nav class="chat-tabs" aria-label="Live chat workspace"><?php foreach($chatTabs as $key=>$label):?><a class="<?=$chatTab===$key?'active':''?>" href="<?=$chatLink($key)?>"><?=e($label)?></a><?php endforeach;?></nav>
<?php if($chatTab==='widgets'):
$editing=isset($_GET['new'])?null:$chatWidget;$cc=$editing?LiveChat::config($editing):LiveChat::defaults();
?><div class="chat-layout"><aside class="card"><h2>Your widgets</h2><a class="button small-button" href="<?=url('/live-chat?tab=widgets&new=1')?>">+ Create widget</a><?php foreach($chatWidgets as $item):?><a class="chat-card-link <?=$editing&&$editing['id']===$item['id']?'selected':''?>" href="<?=url('/live-chat?widget='.$item['id'])?>"><strong><?=e($item['name'])?></strong><p class="small"><?=$item['enabled']?'Enabled':'Disabled'?> &middot; <?=e($item['created_at'])?></p></a><?php endforeach;?></aside><section class="card stack"><h2><?=$editing?'Customize your widget':'Create a chat widget'?></h2><form data-api="chat/widget"><input type="hidden" name="id" value="<?=$editing['id']??0?>"><div class="form-grid">
<?php field('name','Business / widget name','text',$editing['name']??'');?><label>Business information<textarea name="business_info" maxlength="10000" rows="5" required><?=e($editing['business_info']??'')?></textarea><small>Describe your services, products, hours and how you help customers. This is shown to visitors.</small></label>
<label>Allowed website origins<textarea name="allowed_origins" required placeholder="https://example.com"><?=e($editing?implode("\n",json_decode($editing['allowed_origins'],true)):LiveChat::appOrigin())?></textarea><small>One origin per line. Add www and non-www separately. No paths or wildcards.</small></label>
<?php field('color','Primary color','color',$cc['color']);select_field('position','Position',['right'=>'Bottom right','left'=>'Bottom left'],$cc['position']);select_field('button_style','Chat button',['pill'=>'Text pill','circle'=>'Round icon'],$cc['button_style']);select_field('size','Widget size',['compact'=>'Compact','standard'=>'Standard','large'=>'Large'],$cc['size']);field('logo','Logo image URL (HTTPS)','url',$cc['logo'],false);field('avatar','Bot / avatar label','text',$cc['avatar']);field('welcome','Welcome message','text',$cc['welcome']);field('placeholder','Message placeholder','text',$cc['placeholder']);field('offline','Offline message','text',$cc['offline']);
select_field('enabled','Widget availability',['1'=>'Enabled','0'=>'Disabled'],$editing['enabled']??1);select_field('online','Business assistant',['1'=>'Answer from business knowledge','0'=>'Offline / collect messages'],$cc['online']?1:0);
foreach(['mobile'=>'Show on mobile','desktop'=>'Show on desktop','branding'=>'Show SEO AutoPilot branding','notify'=>'In-app notifications for new leads'] as $key=>$label)select_field($key,$label,['1'=>'Yes','0'=>'No'],$cc[$key]?1:0);
?></div><h3>Lead capture fields</h3><div class="form-grid"><?php foreach(['name'=>'Name','phone'=>'Phone number','email'=>'Email','service'=>'Interested service / product','message'=>'Optional message'] as $key=>$label)select_field('field_'.$key,$label,['required'=>'Required','optional'=>'Optional','hidden'=>'Hidden'],$cc['fields'][$key]);?></div><p class="small">At least email or phone must be required. Visitors explicitly agree to be contacted before submission. Branding can be customized on all existing plans.</p><button class="button">Save widget</button><?php if($editing):?> <a class="button secondary" href="<?=$chatLink('embed')?>">Get embed code</a><?php endif;?></form></section></div>
<?php elseif($chatTab==='lead'):
$lead=row('SELECT l.*,w.name AS widget_name FROM chat_leads l JOIN chat_widgets w ON w.id=l.widget_id WHERE l.id=? AND w.user_id=?',[(int)($_GET['id']??0),$user['id']]);if(!$lead)fail('Lead not found.',404);
?><div class="chat-layout"><section class="card"><span class="eyebrow">LEAD DETAILS</span><h2><?=e($lead['name']?:'Website visitor')?></h2><p><?=e($lead['widget_name'])?></p><div class="chat-score"><?=(int)$lead['score']?> / 100</div><p class="small">Contact completeness &amp; buying intent</p><dl class="chat-lead-details"><?php foreach(['phone'=>'Phone','email'=>'Email','service'=>'Interested in','message'=>'Message','status'=>'Status','created_at'=>'Created (UTC)','consent_at'=>'Consent recorded (UTC)'] as $key=>$label):?><dt><?=e($label)?></dt><dd><?=e($lead[$key])?></dd><?php endforeach;?></dl></section><section class="card stack"><h2>Manage follow-up</h2><form data-api="chat/lead"><input type="hidden" name="id" value="<?=$lead['id']?>"><?php select_field('status','Lead status',array_combine(LiveChat::STATUSES,LiveChat::STATUSES),$lead['status']);?><label>Internal notes<textarea name="notes" rows="5" maxlength="5000"><?=e($lead['notes'])?></textarea></label><button class="button">Save lead</button></form><a class="button secondary" href="<?=url('/live-chat?tab=conversations&id='.$lead['conversation_id'])?>">View full conversation</a><h3>Chat history</h3><div class="chat-transcript"><?php foreach(LiveChat::history((int)$lead['conversation_id']) as $message):?><div><small><?=e($message['role'].' · '.$message['created_at'])?></small><?=e($message['body'])?></div><?php endforeach;?></div></section></div>
<?php else:?>
<div class="row"><?php foreach($chatWidgets as $item):?><a class="button secondary small-button" href="<?=url('/live-chat?tab='.$chatTab.'&widget='.$item['id'])?>"><?=e($item['name'])?></a><?php endforeach;?></div>
<?php if(!$chatWidget):empty_state('Create your first widget','Start in Chat Widgets to set up your business and embed code.');
elseif($chatTab==='knowledge'):?>
<div class="chat-layout"><section class="card stack"><h2>Add business knowledge</h2><p class="small">The assistant uses these published answers and your business summary. Include useful keywords and avoid private information. It does not invent answers.</p><form data-api="chat/knowledge"><input type="hidden" name="widget_id" value="<?=$chatId?>"><?php field('question','Question or topic');field('keywords','Matching keywords (e.g. price cost quote)','text','',false);?><label>Confirmed answer<textarea name="answer" required maxlength="4000" rows="6"></textarea></label><button class="button">Add knowledge</button></form></section><section class="card"><h2>Published knowledge</h2><?php foreach(rows('SELECT * FROM chat_knowledge WHERE widget_id=? ORDER BY id',[$chatId]) as $entry):?><div class="chat-card-link"><strong><?=e($entry['question'])?></strong><p><?=e($entry['answer'])?></p><p class="small">Keywords: <?=e($entry['keywords'])?></p><form data-api="chat/knowledge-delete"><input type="hidden" name="widget_id" value="<?=$chatId?>"><input type="hidden" name="id" value="<?=$entry['id']?>"><button class="text-button">Remove entry</button></form></div><?php endforeach;?></section></div>
<?php elseif($chatTab==='embed'):
$snippet='<script src="'.rtrim(cfg('APP_URL'),'/').'/chat-widget.js" data-widget="'.$chatWidget['public_id'].'" defer></script>';
?><div class="chat-layout"><section class="card stack"><h2>One snippet. Any website.</h2><p>Paste this code before the closing body tag, or into your platform’s custom-code area. No framework or plugin installation is needed.</p><textarea class="chat-code" readonly aria-label="Embed code" id="chat-embed-code"><?=e($snippet)?></textarea><button class="button" type="button" data-chat-copy>Copy embed code</button><p role="status" data-chat-copy-status></p><p class="small">Works with PHP, WordPress, Shopify theme custom code, Laravel, React and static HTML. The host platform must allow custom scripts. Your service URL must be publicly reachable over HTTPS for HTTPS websites; localhost is for local testing only.</p><p class="small">If the customer site uses Content Security Policy, allow this service origin for script-src, style-src and connect-src, and your logo origin for img-src. Add the website origin in widget settings before embedding.</p><p class="small">Preview below is the real widget: conversations and submitted leads are saved to your account. Use sample details when testing.</p></section><section class="card"><h2>Live preview</h2><p>Your widget appears in its configured corner. Open it to test knowledge and lead capture.</p><script src="<?=url('/chat-widget.js')?>" data-widget="<?=e($chatWidget['public_id'])?>" defer></script></section></div><script src="<?=url('/assets/js/live-chat-dashboard.js')?>" defer></script>
<?php elseif($chatTab==='conversations'):
$conversationId=(int)($_GET['id']??0);$selected=$conversationId?row('SELECT c.*,w.name AS business_name FROM chat_conversations c JOIN chat_widgets w ON w.id=c.widget_id WHERE c.id=? AND w.user_id=?',[$conversationId,$user['id']]):null;if($conversationId&&!$selected)fail('Conversation not found.',404);
?><div class="chat-layout"><section class="card"><h2>Recent conversations</h2><?php foreach(rows('SELECT c.*,l.name AS lead_name FROM chat_conversations c LEFT JOIN chat_leads l ON l.conversation_id=c.id WHERE c.widget_id=? ORDER BY c.updated_at DESC LIMIT 100',[$chatId]) as $conversation):?><a class="chat-card-link" href="<?=$chatLink('conversations','&id='.$conversation['id'])?>"><strong><?=e($conversation['lead_name']?:'Visitor #'.$conversation['id'])?></strong><p class="small"><?=e($conversation['mode'].' · '.$conversation['updated_at'])?></p></a><?php endforeach;?></section><section class="card stack"><?php if($selected):?><h2><?=e($selected['business_name'])?> &middot; #<?=$selected['id']?></h2><p class="small">Origin: <?=e($selected['origin'])?> &middot; Expires <?=e($selected['expires_at'])?> UTC</p><div class="chat-transcript"><?php foreach(LiveChat::history((int)$selected['id']) as $message):?><div><small><?=e($message['role'].' · '.$message['created_at'])?></small><?=e($message['body'])?></div><?php endforeach;?></div><a class="text-button" href="<?=$chatLink('conversations','&id='.$selected['id'])?>">Refresh conversation</a><form data-api="chat/reply"><input type="hidden" name="id" value="<?=$selected['id']?>"><label>Reply as your team<textarea name="message" required maxlength="2000" rows="3"></textarea></label><p class="small">Sending a reply switches to human mode. Visitors with the widget open receive it within about five seconds.</p><button class="button">Send reply &amp; take over</button></form><form data-api="chat/mode"><input type="hidden" name="id" value="<?=$selected['id']?>"><?php select_field('mode','Conversation mode',['bot'=>'Business assistant','human'=>'Human follow-up','closed'=>'Closed'],$selected['mode']);?><button class="button secondary">Update mode</button></form><?php else:empty_state('Choose a conversation','Read visitor questions, view responses or take over the conversation.');endif;?></section></div>
<?php elseif($chatTab==='leads'||$chatTab==='score'):
$filter=is_string($_GET['status']??null)&&in_array($_GET['status'],LiveChat::STATUSES,true)?$_GET['status']:'';$page=max(1,min(100000,(int)($_GET['page']??1)));$offset=($page-1)*25;$params=[$chatId];$where='widget_id=?';if($filter){$where.=' AND status=?';$params[]=$filter;}$count=(int)value('SELECT COUNT(*) FROM chat_leads WHERE '.$where,$params);$leads=rows('SELECT * FROM chat_leads WHERE '.$where.' ORDER BY '.($chatTab==='score'?'score DESC,id DESC':'id DESC').' LIMIT 25 OFFSET '.$offset,$params);
?><section class="card stack"><h2><?=$chatTab==='score'?'Prioritize your next conversation':'Your leads'?></h2><?php if($chatTab==='score'):?><p class="small">A transparent 0–100 heuristic: name 15, email 25, phone 25, service 20, message 5, and a quote/buy/book/demo/pricing/purchase intent term 10. This is not a prediction of conversion. Contact details are visitor-provided and not independently verified.</p><?php endif;?><div class="row"><a href="<?=$chatLink($chatTab)?>">All</a><?php foreach(LiveChat::STATUSES as $state):?><a href="<?=$chatLink($chatTab,'&status='.$state)?>"><?=e($state)?></a><?php endforeach;?></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Service</th><th>Status</th><th>Score</th><th>Details</th></tr></thead><tbody><?php foreach($leads as $lead):?><tr><td><?=e($lead['name']?:'Visitor')?></td><td><?=e($lead['email'].' '.$lead['phone'])?></td><td><?=e($lead['service'])?></td><td><span class="badge"><?=e($lead['status'])?></span></td><td><?=(int)$lead['score']?> / 100</td><td><a href="<?=$chatLink('lead','&id='.$lead['id'])?>">Open lead &rarr;</a></td></tr><?php endforeach;?></tbody></table></div><?php if(!$leads)empty_state('No leads yet','Submitted contact requests appear here automatically.');?><div class="row"><span><?=$count?> leads &middot; Page <?=$page?></span><?php if($page>1):?><a href="<?=$chatLink($chatTab,'&status='.$filter.'&page='.($page-1))?>">Previous</a><?php endif;if($offset+25<$count):?><a href="<?=$chatLink($chatTab,'&status='.$filter.'&page='.($page+1))?>">Next</a><?php endif;?></div></section>
<?php elseif($chatTab==='automation'):?>
<div class="chat-layout"><section class="card stack"><h2>Lead automation</h2><p class="small">On lead creation, the first matching enabled rule assigns its status. Both the minimum score and optional service/message keyword must match. Rules run in creation order. New is the default status.</p><form data-api="chat/automation"><input type="hidden" name="widget_id" value="<?=$chatId?>"><?php field('name','Rule name');field('keyword','Service/message contains','text','',false);field('min_score','Minimum score (0–100)','number','70');select_field('target_status','Set status',array_combine(LiveChat::STATUSES,LiveChat::STATUSES),'Qualified');select_field('enabled','Rule enabled',['1'=>'Yes','0'=>'No'],'1');?><button class="button">Create rule</button></form></section><section class="card"><h2>Your rules</h2><?php foreach(rows('SELECT * FROM chat_automation_rules WHERE widget_id=? ORDER BY id',[$chatId]) as $rule):?><div class="chat-card-link"><strong><?=e($rule['name'])?></strong><p class="small"><?=e($rule['enabled']?'Enabled':'Disabled')?> &middot; Score &ge; <?=(int)$rule['min_score']?> &middot; <?=e($rule['keyword']?:'Any interest')?> &rarr; <?=e($rule['target_status'])?></p><form data-api="chat/automation-delete"><input type="hidden" name="widget_id" value="<?=$chatId?>"><input type="hidden" name="id" value="<?=$rule['id']?>"><button class="text-button">Remove rule</button></form></div><?php endforeach;?></section></div>
<?php elseif($chatTab==='notifications'):?><section class="card"><h2>Chat notifications</h2><p class="small">New-lead notifications are stored in your account. Enable or disable them per widget. No email or SMS service is required.</p><?php foreach(rows("SELECT * FROM notifications WHERE user_id=? AND path LIKE '/live-chat%' ORDER BY id DESC LIMIT 100",[$user['id']]) as $notice):?><div class="chat-card-link"><a href="<?=url($notice['path'])?>"><?=e($notice['message'])?></a><p class="small"><?=e($notice['created_at'])?> &middot; <?=$notice['read_at']?'Read':'Unread'?></p><?php if(!$notice['read_at']):?><form data-api="notification-read"><input type="hidden" name="id" value="<?=$notice['id']?>"><button class="text-button">Mark read</button></form><?php endif;?></div><?php endforeach;?></section>
<?php elseif($chatTab==='analytics'):
$conversations=(int)value('SELECT COUNT(*) FROM chat_conversations WHERE widget_id=?',[$chatId]);$leads=(int)value('SELECT COUNT(*) FROM chat_leads WHERE widget_id=?',[$chatId]);$converted=(int)value("SELECT COUNT(*) FROM chat_leads WHERE widget_id=? AND status='Converted'",[$chatId]);$average=round((float)value('SELECT AVG(score) FROM chat_leads WHERE widget_id=?',[$chatId]));
?><div class="grid grid-4"><?php foreach(['Conversations'=>$conversations,'Captured leads'=>$leads,'Lead capture rate'=>($conversations?round($leads/$conversations*100,1):0).'%','Converted leads'=>$converted] as $label=>$metric):?><div class="card metric"><span class="metric-label"><?=e($label)?></span><div class="metric-value"><?=e($metric)?></div></div><?php endforeach;?></div><div class="card stack"><h2>Last 7 days · new leads</h2><p class="small">Actual saved data in UTC. Average lead score: <?=$average?> / 100. Lead capture rate is leads divided by started conversations, not page visitors.</p><div class="chat-analytics"><?php $daily=rows('SELECT DATE(created_at) AS day,COUNT(*) AS total FROM chat_leads WHERE widget_id=? AND created_at>=DATE_SUB(CURDATE(),INTERVAL 6 DAY) GROUP BY DATE(created_at)',[$chatId]);$days=array_column($daily,'total','day');for($i=6;$i>=0;$i--):$day=date('Y-m-d',strtotime('-'.$i.' days'));?><div class="chat-day"><strong><?=(int)($days[$day]??0)?></strong><span><?=e(date('D, M j',strtotime($day)))?></span></div><?php endfor;?></div></div>
<?php endif;endif;?>
