<?php
$localInput=static function(string $key,string $label,string $type='text',int $max=300,string $default='')use($p){$val=$p[$key]??$default;?><label><?=e($label)?><input name="<?=e($key)?>" type="<?=e($type)?>" value="<?=e($val)?>" <?=$key==='business_name'?'required':''?> <?php if($type==='number'):?>min="<?=$key==='rating'?1:0?>" max="<?=$key==='rating'?5:10000000?>" step="<?=$key==='rating'?'0.01':'1'?>"<?php elseif($type==='date'):?>max="<?=date('Y-m-d')?>"<?php else:?>maxlength="<?=$max?>"<?php endif;?>></label><?php };
$localArea=static function(string $key,string $label,int $max=3000,int $rows=3)use($p){$value=$p[$key]??'';if(is_array($value))$value=implode("\n",$value);?><label><?=e($label)?><textarea name="<?=e($key)?>" rows="<?=$rows?>" maxlength="<?=$max?>"><?=e($value)?></textarea></label><?php };
?>
<form data-api="local-seo-audit" id="local-profile-form"><input type="hidden" name="admin_context" value="<?=($localSeoRoute??'')==='/admin/local-seo'?'1':'0'?>"><input type="hidden" name="website_id" value="<?=$wid?>">
<div class="local-seo-form-block"><h3>1. Business profile</h3><p class="small">Use the details shown on your profile. Leave unknown values blank; only the business name is required.</p><div class="form-grid">
<?php $localInput('business_name','Business name','text',190);$localInput('category','Primary business category','text',100);select_field('business_type','Business type',['storefront'=>'Storefront · customers visit this address','service_area'=>'Service area · hide the street address','hybrid'=>'Hybrid · storefront and service area'],$p['business_type']??'storefront');$localInput('phone','Business phone · include country code','tel',40);$localInput('website','Business website','url',1000,$w['domain']);$localInput('profile_url','Google Business Profile link · optional','url',1000);?>
</div><?php $localArea('description','Business description',1500);$localArea('secondary_categories','Additional categories · one per line, up to 10',2000,2);?>
<h3>Location</h3><p class="small">For service-area businesses, the public service area is used for scoring and schema. Entered street details are stored in the private audit but omitted from generated schema.</p><div class="form-grid"><?php $localInput('street','Street address','text',300);$localInput('city','City / locality','text',100);$localInput('region','State / region','text',100);$localInput('postal_code','Postal code','text',30);$localInput('country','Two-letter country code · e.g. IN or US','text',2);$localInput('service_area','Service area · e.g. Pune and nearby towns','text',300);?></div>
</div>
<details class="local-seo-input-group"><summary>2. Reviews, photos &amp; services</summary><p class="small">Enter counts from the same profile and point in time. Blank means unknown; zero means none.</p><div class="form-grid"><?php $localInput('rating','Average rating · 1 to 5','number');$localInput('review_count','Total reviews','number');$localInput('replied_reviews','Reviews with a business reply','number');$localInput('last_review_date','Date of most recent review','date');$localInput('photo_count','Profile photo count','number');$localInput('image_url','Public business image URL · for schema','url',1000);?></div><?php $localArea('services','Services · one per line, up to 30',6000,4);?></details>
<details class="local-seo-input-group"><summary>3. Weekly opening hours</summary><p class="small">Choose a state for each day. Closing earlier than opening represents an overnight schedule. Special dates and split shifts should be added to the final schema manually.</p>
<?php foreach(LocalSeo::DAYS as $day):$hours=$p['hours'][$day]??['state'=>'unknown','opens'=>'','closes'=>''];?><div class="local-hours" data-local-hours><strong><?=e($day)?></strong><label>Status<select name="hours[<?=e($day)?>][state]" data-hours-state><?php foreach(['unknown'=>'Not entered','open'=>'Open · set times','closed'=>'Closed','all_day'=>'Open 24 hours'] as $value=>$label):?><option value="<?=$value?>" <?=$hours['state']===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label>Opens<input type="time" name="hours[<?=e($day)?>][opens]" value="<?=e($hours['opens'])?>" data-hours-time></label><label>Closes<input type="time" name="hours[<?=e($day)?>][closes]" value="<?=e($hours['closes'])?>" data-hours-time></label></div><?php endforeach;?>
</details>
<details class="local-seo-input-group"><summary>4. NAP consistency · Name, Address, Phone</summary><p class="small">Paste the full details from your website and one directory. Include city, region, postal code and country in the address. For service-area businesses, enter the public service area instead. This compares only the text you supply; it does not search other sites.</p>
<h3>Details on your website</h3><div class="form-grid"><?php $localInput('website_name','Name on website','text',190);$localInput('website_phone','Phone on website','tel',40);?></div><?php $localArea('website_address','Full address or service area on website',700,2);?>
<h3>Details on a directory</h3><div class="form-grid"><?php $localInput('directory_source','Directory name / source · e.g. Bing Places','text',200);$localInput('directory_name','Name on directory','text',190);$localInput('directory_phone','Phone on directory','tel',40);?></div><?php $localArea('directory_address','Full address or service area on directory',700,2);?></details>
<details class="local-seo-input-group"><summary>5. Website SEO &amp; target keywords</summary><p class="small">Paste content from the local landing page. We do not fetch or inspect your website.</p>
<?php $localInput('page_title','Actual page title','text',300);$localArea('meta_description','Actual meta description',600,2);$localInput('h1','Actual H1 / main heading','text',300);$localArea('page_text','Page body text',10000,6);?>
<div class="form-grid"><?php foreach(['mobile_friendly'=>'Have you checked mobile usability?','indexable'=>'Have you confirmed the page can be indexed?'] as $key=>$label)select_field($key,$label,['unknown'=>'Not checked','yes'=>'Yes','no'=>'No'],$p[$key]??'unknown');?></div>
<?php $localArea('keywords','Target keyword phrases · one per line, up to 30',6000,3);?></details>
<details class="local-seo-input-group"><summary>6. LocalBusiness schema</summary><p class="small">Select a type for the new schema draft. If schema already exists on your website, paste its JSON here for the audit. Generated drafts are not treated as installed schema.</p>
<?php select_field('schema_type','Schema type',array_combine(LocalSeo::TYPES,LocalSeo::TYPES),$p['schema_type']??'LocalBusiness');$localArea('existing_schema','Existing website JSON-LD · JSON only, without script tags',30000,7);?>
<p class="small">The draft includes only entered business details, hours and services. Reported Google ratings and review totals are kept in the audit and omitted from review markup.</p></details>
<div class="row local-seo-actions"><button class="button" type="submit">Analyze &amp; save audit</button><button class="button secondary" type="button" data-local-schema>Generate schema only</button></div>
<p class="small">The score uses published app thresholds, not Google’s ranking weights. Missing comparison data earns no points and is marked Not provided.</p>
<div data-local-schema-feedback class="form-feedback" role="status" hidden></div>
<section class="local-schema-preview" data-local-schema-preview hidden><h3>LocalBusiness schema draft</h3><pre id="local-schema-draft" tabindex="0"></pre><div class="row local-seo-actions"><button type="button" class="button secondary" data-local-copy="local-schema-draft">Copy JSON-LD</button><button type="button" class="button secondary" data-local-download="local-schema-draft">Download JSON-LD</button></div><p class="small">Review incomplete fields and publish only accurate, public business information. Wrap the JSON in a script tag with type application/ld+json when adding it to your website.</p></section>
</form>
