<?php
$recordNames=['keywords'=>'keyword','competitors'=>'competitor','backlinks'=>'backlink','content'=>'content project','tasks'=>'task','human-services'=>'service request'];
$recordName=$recordNames[$section]??'record';
?>
<?php
if($section==='backlinks')require ROOT.'/dashboard/backlink-checker.php';
$def=$defs[$section];$page=max(1,min(10000,(int)($_GET['page']??1)));$search=trim((string)($_GET['q']??''));$first=array_key_first($def['fields']);$where='website_id=?';$params=[$wid];if($search!==''){$where.=" AND $first LIKE ?";$params[]='%'.mb_substr($search,0,190).'%';}$count=(int)value('SELECT COUNT(*) FROM '.$def['table'].' WHERE '.$where,$params);$selection=$section==='keywords'?"*,(SELECT position FROM keyword_rankings r WHERE r.keyword_id=keywords.id ORDER BY date DESC LIMIT 1) AS current_position,(SELECT source FROM keyword_rankings r WHERE r.keyword_id=keywords.id ORDER BY date DESC LIMIT 1) AS ranking_source":'*';$records=rows('SELECT '.$selection.' FROM '.$def['table'].' WHERE '.$where.' ORDER BY id DESC LIMIT 25 OFFSET '.(($page-1)*25),$params);
if($section==='keywords')echo '<div class="welcome-banner"><div><h3>Ready to see where you rank?</h3><p>Add your keywords here, then check their Google positions and track changes.</p></div><a class="button" href="'.url('/rankings?website_id='.$wid).'">Check Google rankings</a></div>';
$edit=null;if(isset($_GET['edit']))$edit=row('SELECT * FROM '.$def['table'].' WHERE id=? AND website_id=?',[(int)$_GET['edit'],$wid]);
?><div class="card"><div class="card-header"><h3><?=number_format($count)?> <?=e($recordName.'s')?></h3><div class="row"><?php if(in_array($section,['keywords','backlinks'])):?><a class="button secondary small-button" href="<?=url('/api/v1/export?module='.$section.'&website_id='.$wid)?>">↓ Export CSV</a><?php endif;?><a class="button small-button" href="#create">+ Add <?=e($recordName)?></a></div></div><form method="get" class="row"><input type="hidden" name="website_id" value="<?=$wid?>"><label class="full">Search<input name="q" value="<?=e($search)?>" placeholder="Search <?=e($section)?>…"></label><button class="button secondary small-button">Search</button></form><div class="table-wrap"><table><thead><tr><?php foreach($def['columns'] as $label):?><th><?=e($label)?></th><?php endforeach;?><th>Actions</th></tr></thead><tbody><?php foreach($records as $r):?><tr><?php foreach($def['columns'] as $key=>$label):?><td><?php if($key==='current_position'):?><?=e(Ranking::label($r[$key]===null?null:(int)$r[$key],$r['ranking_source']))?><?php elseif(in_array($key,['status','priority','source'])):?><span class="badge <?=e($r[$key])?>"><?=e(str_replace('_',' ',$r[$key]))?></span><?php else:?><?=e($r[$key]??'—')?><?php endif;?></td><?php endforeach;?><td><a href="<?=url('/'.$section.'?website_id='.$wid.'&edit='.$r['id'].'#create')?>">Edit</a> · <button class="text-button" data-action="delete" data-module="<?=e($section)?>" data-website-id="<?=$wid?>" data-id="<?=$r['id']?>" data-confirm="Delete this record permanently?">Delete</button><?php if($section==='content'):?><br><a href="<?=url('/content?website_id='.$wid.'&brief='.$r['id'])?>">Open brief →</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$records)empty_state('A clean slate, ready for your next move.','Add your first record using the form below.');?><nav class="pagination" aria-label="Pagination"><?php if($page>1):?><a href="?website_id=<?=$wid?>&page=<?=$page-1?>&q=<?=urlencode($search)?>">← Previous</a><?php endif;?><span>Page <?=$page?> of <?=max(1,ceil($count/25))?></span><?php if($count>$page*25):?><a href="?website_id=<?=$wid?>&page=<?=$page+1?>&q=<?=urlencode($search)?>">Next →</a><?php endif;?></nav></div>
<div class="card stack" id="create"><h2><?=$edit?'Edit '.e($recordName):'Add a '.e($recordName)?></h2><form data-api="save"><input type="hidden" name="module" value="<?=e($section)?>"><input type="hidden" name="website_id" value="<?=$wid?>"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>"><div class="form-grid"><?php foreach($def['fields'] as $key=>$label){if(is_array($label))select_field($key,$label[0],array_combine($label[1],array_map(fn($v)=>ucwords(str_replace('_',' ',$v)),$label[1])),$edit[$key]??'');elseif(in_array($key,['notes','description']))echo '<label>'.e($label).'<textarea name="'.e($key).'">'.e($edit[$key]??'').'</textarea></label>';else field($key,$label,$key==='due_date'?'date':($key==='budget'?'number':(str_contains($key,'url')||$key==='domain'?'url':'text')),$edit[$key]??(['country'=>'India','language'=>'en','search_engine'=>'google'][$key]??''),$key===$first || $key==='budget');}?></div><button class="button">Save <?=e($section==='human-services'?'request':'record')?> →</button></form></div>
<?php if(in_array($section,['keywords','backlinks'])):?><div class="card stack"><h3>Import CSV</h3><p class="small">UTF-8 CSV, up to 2 MB and 1,000 rows. Headers: <?=$section==='keywords'?'keyword,country,language,device,target_url,intent,tags,search_volume,difficulty,position':'source_url,target_url,anchor,follow,status,domain_rating'?>. Imports are atomic; invalid rows reject the file.</p><form data-api="import" enctype="multipart/form-data"><input type="hidden" name="module" value="<?=e($section)?>"><input type="hidden" name="website_id" value="<?=$wid?>"><?php field('csv','CSV file','file');?><button class="button secondary">Import CSV</button></form></div><?php endif; if($section==='content'&&isset($_GET['brief'])){$project=row('SELECT * FROM content_projects WHERE id=? AND website_id=?',[(int)$_GET['brief'],$wid]);if($project){$brief=row('SELECT * FROM content_briefs WHERE content_project_id=? ORDER BY id DESC LIMIT 1',[$project['id']]);?><div class="card stack"><h2><?=e($project['topic'])?> — content brief</h2><form data-api="content-brief" data-output="brief-output"><input type="hidden" name="website_id" value="<?=$wid?>"><input type="hidden" name="id" value="<?=$project['id']?>"><button class="button">✧ Generate with AI</button></form><pre id="brief-output"><?=e($brief['content']??'No brief saved yet. AI requires provider configuration.')?></pre><form data-api="save-brief"><input type="hidden" name="website_id" value="<?=$wid?>"><input type="hidden" name="id" value="<?=$project['id']?>"><label>Write or edit a brief<textarea name="content" required><?=e($brief['content']??'')?></textarea></label><button class="button secondary">Save manual brief</button></form></div><?php }}?>

<?php if($section==='content'):?><div class="card stack"><h3>Write with AI</h3><p>Generate titles, keyword ideas, complete blogs and articles, or humanize your full draft.</p><a class="button" href="<?=url('/ai-assistant?website_id='.$wid.'#writing-tools')?>">Open AI writing tools</a></div><?php endif;?>
