<?php
$connected=cfg('RANKING_ENDPOINT')&&cfg('RANKING_API_KEY');
$isHasData=rtrim((string)cfg('RANKING_ENDPOINT'),'/')==='https://api.hasdata.com/scrape/google/serp';
$tracked=rows('SELECT k.*,r.position,r.date,r.url,r.source AS ranking_source,(SELECT position FROM keyword_rankings p WHERE p.keyword_id=k.id AND p.date<r.date ORDER BY p.date DESC LIMIT 1) AS previous_position FROM keywords k LEFT JOIN keyword_rankings r ON r.keyword_id=k.id AND r.date=(SELECT MAX(date) FROM keyword_rankings x WHERE x.keyword_id=k.id) WHERE k.website_id=? ORDER BY k.keyword,k.id',[$wid]);
$checked=0;$top=0;$sum=0;$found=0;$pending=[];
foreach($tracked as $k){if($k['date']===date('Y-m-d')&&$k['ranking_source']===Ranking::source())$checked++;elseif(strtolower($k['search_engine'])==='google')$pending[]=(int)$k['id'];if($k['position']!==null){$found++;$sum+=(int)$k['position'];if($k['position']<=10)$top++;}}
?>
<section class="ranking-hero"><div><span class="eyebrow">SEARCH PERFORMANCE</span><h2>Your Google rankings, at a glance.</h2><p>See where your website appears and which keywords need attention.</p><div class="row"><span class="badge <?=$connected?'completed':''?>"><?=$connected?($isHasData?'HasData connected':'Ranking provider connected'):'Provider not connected'?></span><span class="small"><?=$isHasData?'Search depth: up to 100 positions':'Organic search positions'?></span></div></div><div class="ranking-actions"><button class="button" data-check-rankings data-website-id="<?=$wid?>" data-keywords="<?=e(json_encode($pending))?>" <?=!$connected||!$pending?'disabled':''?>><?=$pending?'Check Google rankings':($tracked?'Up to date today':'Add keywords to start')?></button><a class="button secondary" href="<?=url('/keywords?website_id='.$wid.'#create')?>">+ Add keywords</a></div></section>
<div id="ranking-progress" class="alert" role="status" aria-live="polite" hidden></div>
<?php if(!$connected):?><div class="alert">Connect a ranking API in Administration &gt; Settings to run live checks. Imported rankings remain available.</div><?php endif;?>
<div class="grid grid-4 stack"><?php foreach([['Tracked keywords',count($tracked),'Keywords in this project'],['Checked today',$checked,'Live checks saved today (UTC)'],['In the top 10',$top,'Based on latest saved positions'],['Average position',$found?number_format($sum/$found,1):'—','Ranked keywords only · Lower is better']] as [$label,$number,$help]):?><article class="card metric"><div class="metric-label"><?=e($label)?></div><div class="metric-value"><?=e($number)?></div><div class="metric-foot"><?=e($help)?></div></article><?php endforeach;?></div>
<section class="card stack"><div class="card-header"><div><h3>Keyword performance</h3><p class="small">Results reflect each keyword's country, language and device. One saved live check per keyword per day.</p></div><a href="<?=url('/keywords?website_id='.$wid)?>" class="button secondary small-button">Manage keywords</a></div>
<?php if($isHasData):?><p class="ranking-note">Checks search up to 100 organic positions, stopping when your target is found or Google returns no further pages. “Not found” means your domain or target URL did not appear in those results. Leave Target URL empty to match your domain and subdomains. A keyword check can use up to 10 HasData requests and account credits. A homepage Target URL matches only that homepage; clear it to track any page on your domain.</p><?php endif;?>
<label class="ranking-filter">Find a keyword<input type="search" data-ranking-filter placeholder="Filter keywords on this page…"></label>
<div class="table-wrap"><table id="ranking-table"><thead><tr><th>Keyword</th><th>Position</th><th>Change</th><th>Audience</th><th>Last checked</th><th>Ranking page</th></tr></thead><tbody>
<?php foreach($tracked as $k):$change=$k['position']!==null&&$k['previous_position']!==null?(int)$k['previous_position']-(int)$k['position']:null;?><tr data-ranking-row><td><strong><?=e($k['keyword'])?></strong><br><span class="small"><?=e(ucfirst($k['search_engine']))?></span></td><td><span class="badge <?=$k['position']!==null&&$k['position']<=10?'completed':''?>"><?=e(Ranking::label($k['position']===null?null:(int)$k['position'],$k['ranking_source']))?></span></td><td><span class="<?=($change??0)>0?'rank-up':(($change??0)<0?'rank-down':'small')?>"><?=e($change===null?'—':($change===0?'No change':($change>0?'↑ '.$change:'↓ '.abs($change))))?></span></td><td><?=e($k['country'])?><br><span class="small"><?=e($k['language'].' · '.$k['device'])?></span></td><td><?=e($k['date']??'—')?><br><span class="small"><?=e(in_array($k['ranking_source'],['api','hasdata_top100'])?'Live API':($k['ranking_source']??''))?></span></td><td><?php if($k['url']):?><a class="ranking-url" href="<?=e($k['url'])?>" target="_blank" rel="noopener noreferrer"><?=e($k['url'])?></a><?php else:?>—<?php endif;?></td></tr><?php endforeach;?>
</tbody></table></div><?php if(!$tracked)empty_state('Start with your first keyword','Add the searches customers use to find your business, then check their Google rankings.');?><p data-ranking-empty class="small" hidden>No keywords match your search.</p></section>
<?php $history=rows('SELECT r.date AS label,AVG(r.position) AS value FROM keyword_rankings r JOIN keywords k ON k.id=r.keyword_id WHERE k.website_id=? AND r.date>=DATE_SUB(CURDATE(),INTERVAL 90 DAY) AND r.position IS NOT NULL GROUP BY r.date ORDER BY r.date',[$wid]);?>
<section class="card stack"><div class="card-header"><div><h3>Ranking trend</h3><p class="small">Average recorded position over 90 days. Lower is better; missing positions are excluded.</p></div><span class="badge">90 days</span></div><?php Chart::line($history,'Average keyword position over 90 days');?></section>
<?php require ROOT.'/dashboard/tools.php';?>
