<?php if($section==='keywords'): require ROOT.'/dashboard/keyword-analysis.php';?>
<div class="card"><h3>Bulk add keywords</h3><form data-api="keyword-bulk"><input type="hidden" name="website_id" value="<?=$wid?>"><label>One keyword per line<textarea name="keywords" required rows="7" placeholder="technical seo audit&#10;seo reporting software"></textarea></label><button class="button">Add keywords</button></form></div>
<?php elseif($section==='tasks'):?>
<div class="card"><h3>Assign a task</h3><form data-api="assign-task"><input type="hidden" name="website_id" value="<?=$wid?>"><div class="form-grid"><?php $taskOptions=[];foreach(rows('SELECT id,title FROM seo_tasks WHERE website_id=? ORDER BY id DESC LIMIT 500',[$wid]) as $r)$taskOptions[$r['id']]=$r['title'];select_field('id','Task',$taskOptions);$people=[$w['user_id']=>'Project owner'];foreach(rows('SELECT u.id,u.name FROM users u JOIN team_members t ON t.user_id=u.id WHERE t.website_id=?',[$wid]) as $r)$people[$r['id']]=$r['name'];select_field('assigned_user','Assign to',$people);?></div><button class="button">Assign task</button></form></div>
<?php elseif($section==='competitors'):?>
<div class="card"><h3>Record competitor keyword data</h3><p class="small">Manual research only. Enter a position you verified from your chosen source.</p><form data-api="competitor-keyword"><input type="hidden" name="website_id" value="<?=$wid?>"><div class="form-grid"><?php $options=[];foreach(rows('SELECT id,domain FROM competitors WHERE website_id=?',[$wid]) as $r)$options[$r['id']]=$r['domain'];select_field('competitor_id','Competitor',$options);field('keyword','Keyword');field('position','Verified position','number');?></div><button class="button">Save keyword</button></form></div><div class="card"><h3>Keyword gap</h3><p class="small">Recorded competitor keywords missing from this project’s keyword list.</p><?php table(['domain'=>'Competitor','keyword'=>'Keyword','position'=>'Position','source'=>'Source'],rows('SELECT c.domain,ck.keyword,ck.position,ck.source FROM competitor_keywords ck JOIN competitors c ON c.id=ck.competitor_id WHERE c.website_id=? AND NOT EXISTS(SELECT 1 FROM keywords k WHERE k.website_id=c.website_id AND k.keyword=ck.keyword) LIMIT 100',[$wid]));?></div><div class="card"><h3>Content gap candidates</h3><p class="small">Competitor keywords not mentioned in the titles of your latest crawled pages. Review search intent before planning content.</p><?php table(['keyword'=>'Keyword','domain'=>'Competitor'],rows('SELECT DISTINCT ck.keyword,c.domain FROM competitor_keywords ck JOIN competitors c ON c.id=ck.competitor_id WHERE c.website_id=? AND NOT EXISTS(SELECT 1 FROM pages p WHERE p.website_id=c.website_id AND p.job_id=(SELECT MAX(j.id) FROM crawl_jobs j WHERE j.website_id=c.website_id AND j.status="completed") AND p.title LIKE CONCAT("%",ck.keyword,"%")) LIMIT 100',[$wid]));?></div>
<?php elseif($section==='team'):?>
<div class="card"><h3>Invite a new team member</h3><form data-api="invite"><input type="hidden" name="website_id" value="<?=$wid?>"><?php field('email','Email address','email');?><button class="button">Send invitation</button></form><p class="small">Invitations expire in seven days. The recipient must register or sign in with the invited email.</p></div>
<?php endif;?>
