<?php if($section==='ai-assistant'):?>
<?php require ROOT.'/dashboard/ai-writing.php'; ?>
<details class="card assistant-chat"><summary>Ask your SEO assistant &amp; view history<span>Get help with this project’s audit, prioritize fixes, or revisit your saved drafts. Expand to open →</span></summary><div>
<div id="chat"><?php $messages=rows('SELECT m.role,m.content FROM ai_messages m JOIN ai_conversations c ON c.id=m.conversation_id WHERE c.user_id=? AND c.website_id=? ORDER BY m.id DESC LIMIT 20',[$user['id'],$wid]);foreach(array_reverse($messages) as $m):?><div class="chat-message <?=e($m['role'])?>"><?=e($m['content'])?></div><?php endforeach;if(!$messages):?><p class="small">Your saved conversations and writing drafts will appear here.</p><?php endif;?></div>
<form data-api="ai" data-reload="false"><input type="hidden" name="website_id" value="<?=$wid?>"><label>Your question<textarea name="message" maxlength="6000" placeholder="What should I fix first on my website?" required></textarea></label><button class="button">Ask assistant ↗</button></form>
</div></details>
<?php elseif($section==='schema'):?>
<div class="grid grid-2"><div class="card"><h3>Schema generator</h3><p class="small">Generate syntactically valid JSON-LD. Search-engine eligibility depends on the schema type, required properties and your actual page content.</p><form data-api="schema" data-output="schema-output"><input type="hidden" name="website_id" value="<?=$wid?>"><?php select_field('type','Schema type',array_combine(Schema::types(),Schema::types()));?><label>JSON properties<textarea name="json" rows="12" required><?=e(json_encode(['name'=>$w['name'],'url'=>$w['domain']],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></textarea></label><button class="button">Generate JSON-LD</button></form></div><div class="card"><h3>Preview</h3><pre id="schema-output">Your generated JSON-LD will appear here.</pre><button class="button secondary" data-copy-schema>Copy JSON-LD</button><p class="small">Review and validate structured data before publishing. This tool does not inject code into your website.</p></div></div>
<?php elseif($section==='rankings'):?>
<div class="card"><h3>Ranking history</h3><?php if((!cfg('RANKING_ENDPOINT')||!cfg('RANKING_API_KEY'))):?><div class="alert">Ranking API not configured. CSV-imported positions remain available and are labeled as imported data.</div><?php endif;?><nav class="tabs"><?php foreach([1=>'Today',2=>'Yesterday + today',7=>'7 days',30=>'30 days',90=>'90 days'] as $days=>$label):?><a class="<?=((int)($_GET['days']??30)===$days)?'active':''?>" href="?website_id=<?=$wid?>&days=<?=$days?>"><?=e($label)?></a><?php endforeach;?></nav><?php $days=(int)($_GET['days']??30);if(!in_array($days,[1,2,7,30,90]))$days=30;$rankings=rows('SELECT k.keyword,r.date,r.position,r.url,k.country,k.device,r.source FROM keyword_rankings r JOIN keywords k ON k.id=r.keyword_id WHERE k.website_id=? AND r.date>=DATE_SUB(CURDATE(),INTERVAL ? DAY) ORDER BY r.date DESC,k.keyword LIMIT 300',[$wid,$days-1]);foreach($rankings as &$rankingRow)$rankingRow['position']=Ranking::label($rankingRow['position']===null?null:(int)$rankingRow['position'],$rankingRow['source']);unset($rankingRow);table(['keyword'=>'Keyword','date'=>'Date','position'=>'Position','url'=>'Ranking URL','country'=>'Country','device'=>'Device','source'=>'Source'],$rankings);?></div>
<?php elseif($section==='research'):?>
<div class="card"><h3>Keyword research</h3><?php if(!cfg('KEYWORD_ENDPOINT')):?><div class="alert">Keyword research data source unavailable. Import verified search volume, difficulty and keyword data using the keyword CSV importer. No metrics are estimated or fabricated.</div><?php else:?><p>Research uses your configured keyword gateway. Metrics are supplied by that provider.</p><?php endif;?><a class="button" href="<?=url('/keywords?website_id='.$wid)?>">Open keywords & CSV import ↗</a></div>
<?php elseif($section==='automations'):?>
<div class="card"><h3>Let your audit start the next step.</h3><p>Enabled rules create tasks when a new audit finds a matching issue. Rules never change your website content.</p><?php foreach(['missing_description'=>'Missing meta description → create a task','long_title'=>'Long title → create a recommendation task','http_error'=>'HTTP error → create a critical task','sitemap'=>'Missing sitemap → create a technical task'] as $code=>$label):$enabled=value('SELECT enabled FROM automation_rules WHERE website_id=? AND code=?',[$wid,$code]);?><form data-api="automation" class="issue row between"><input type="hidden" name="website_id" value="<?=$wid?>"><input type="hidden" name="code" value="<?=e($code)?>"><label class="check"><input type="checkbox" name="enabled" <?=$enabled?'checked':''?>><?=e($label)?></label><button class="button secondary small-button">Save rule</button></form><?php endforeach;?></div>
<?php elseif($section==='internal-links'):?>
<div class="card"><div class="card-header"><h3>Connect your content.</h3><button class="button" data-action="find-links" data-website-id="<?=$wid?>">Find opportunities</button></div><p class="small">Suggestions match page headings to mentions in other crawled pages, excluding existing links. Analysis is limited to 300 pages per run.</p><?php $links=rows('SELECT * FROM internal_link_suggestions WHERE website_id=? ORDER BY id DESC LIMIT 100',[$wid]);foreach($links as $link):?><article class="issue"><h3><?=e($link['anchor'])?></h3><p><?=e($link['source_url'])?> → <?=e($link['target_url'])?></p><span class="badge"><?=e($link['status'])?></span><div class="row"><?php foreach(['accepted','rejected','implemented'] as $status):?><button class="text-button" data-action="link-status" data-id="<?=$link['id']?>" data-website-id="<?=$wid?>" data-status="<?=$status?>"><?=ucfirst($status)?></button><?php endforeach;?></div></article><?php endforeach;if(!$links)empty_state('Build useful connections.','Run the analysis after crawling your website.');?></div>
<?php elseif($section==='team'):?>
<div class="card"><h3>Good SEO is a team effort.</h3><p>Assign registered members to this website. Assigned members can work with this project’s audits, content, tasks and reports. Billing and access management remain with the owner.</p><?php $members=rows('SELECT t.id,u.name,u.email FROM team_members t JOIN users u ON u.id=t.user_id WHERE t.website_id=?',[$wid]);foreach($members as $m):?><div class="issue row between"><span><?=e($m['name'])?> · <?=e($m['email'])?></span><button class="text-button" data-action="team-remove" data-id="<?=$m['id']?>" data-website-id="<?=$wid?>">Remove access</button></div><?php endforeach;?><form data-api="team"><input type="hidden" name="website_id" value="<?=$wid?>"><?php field('email','Registered member email','email');?><button class="button">Assign member</button></form></div><div class="card stack"><h3>White-label reporting</h3><p class="small">Agency plan required. Branding is saved into newly generated report snapshots.</p><form data-api="branding"><input type="hidden" name="website_id" value="<?=$wid?>"><div class="form-grid"><?php foreach(['agency_name'=>'Agency name','agency_website'=>'Agency website','agency_contact'=>'Contact information','report_footer'=>'Report footer','brand_color'=>'Brand color','logo_url'=>'Logo URL'] as $k=>$v)field($k,$v,'text',value('SELECT value FROM website_settings WHERE website_id=? AND name=?',[$wid,$k])?:($k==='brand_color'?'#ff7a00':''),false);?></div><button class="button">Save branding</button></form></div>
<?php else: fail('Page not found.',404);endif;?>
