<?php $expertStandalone=$expertStandalone??false; ?>
<link rel="stylesheet" href="<?=url('/assets/css/seo-expert.css')?>">
<section class="expert-service section-pad container" id="hire-seo-expert" itemscope itemtype="https://schema.org/Service">
<meta itemprop="name" content="Hire an SEO Expert"><meta itemprop="serviceType" content="SEO strategy and optimization">
<div class="expert-hero"><div><span class="eyebrow">EXPERT STRATEGY. MEASURABLE PROGRESS.</span><p class="expert-pill">90-Day SEO Growth Program</p><<?=$expertStandalone?'h1':'h2'?>>Hire an SEO Expert &amp; Grow Your <em>Google Visibility</em></<?=$expertStandalone?'h1':'h2'?>>
<p class="expert-intro" itemprop="description">Get a dedicated SEO expert, customized strategy, technical optimization, content planning and monthly progress tracking.</p>
<div class="expert-actions"><a class="button" data-expert-open="audit" href="<?=url('/hire-seo-expert?enquire=1&type=audit#expert-enquiry')?>">Get Free SEO Audit ↗</a><a class="button secondary" data-expert-open="hire" href="<?=url('/hire-seo-expert?enquire=1#expert-enquiry')?>">Hire SEO Expert</a><a class="expert-text-link" href="#expert-plans">View SEO Plans ↓</a></div><p class="small">Results-focused SEO strategy. Clear priorities. Monthly progress tracking.</p></div>
<aside class="expert-roadmap"><div class="expert-roadmap-heading"><span>YOUR NEXT 90 DAYS</span><span class="expert-pill">Built around your business</span></div><h3>A clear plan.<br>A real expert.<br><em>Consistent progress.</em></h3><ol><li><b>01</b><div><strong>Audit &amp; Fix</strong><p>Find technical roadblocks and set your baseline.</p></div></li><li><b>02</b><div><strong>Optimize &amp; Grow</strong><p>Improve pages and build your content direction.</p></div></li><li><b>03</b><div><strong>Scale &amp; Improve</strong><p>Review performance and prioritize the next wins.</p></div></li></ol></aside></div>
<div class="expert-plan-heading" id="expert-plans"><div><span class="eyebrow">YOUR BUSINESS. YOUR GROWTH PLAN.</span><h2>Expert SEO, clearly priced.</h2><p>Total program prices in INR. Longer programs lower your monthly equivalent.</p></div><label class="expert-duration-label">Program duration<select data-expert-duration><option value="3">3 Months</option><option value="6">6 Months</option><option value="12">1 Year</option></select></label></div>
<?php foreach(SeoExpert::DURATIONS as $months=>$duration):?><div class="expert-pricing" data-expert-pricing="<?=$months?>"><h3 class="expert-duration-heading"><?=e($duration)?> programs</h3><div class="expert-plan-grid">
<?php foreach(SeoExpert::PLANS as $key=>$name):$price=SeoExpert::price($key,$months);$savings=SeoExpert::savings($key,$months);?><article class="expert-plan <?=$key==='growth'?'expert-popular':''?>" itemscope itemprop="offers" itemtype="https://schema.org/Offer"><meta itemprop="priceCurrency" content="INR"><meta itemprop="price" content="<?=$price/100?>"><meta itemprop="name" content="<?=e($name.' SEO – '.$duration)?>"><link itemprop="url" href="<?=e(rtrim(cfg('APP_URL'),'/').'/hire-seo-expert?plan='.$key.'&duration='.$months.'&enquire=1')?>">
<div class="expert-plan-top"><h3><?=e($name)?></h3><?php if($key==='growth'):?><span class="expert-pill">Most Popular</span><?php endif;?></div><p><?=e(['starter'=>'Build a stronger search foundation.','growth'=>'Turn your strategy into steady action.','pro'=>'Get focused, dedicated SEO support.'][$key])?></p><div class="expert-price"><?=money($price)?><small>total / <?=e($duration)?></small></div><p><strong><?=money((int)round($price/$months))?> / month equivalent</strong></p><p class="expert-saving"><?=$savings['total']>0?'Save '.money((int)$savings['total']).' ('.$savings['percent'].'%) · '.money((int)round($savings['monthly'])).'/mo less':'Base program · no long-term commitment'?></p>
<ul><?php $features=['SEO Audit','Keyword Research','On-Page SEO','Technical SEO','Content Strategy','Competitor Analysis','Ranking Monitoring','Monthly SEO Report'];if($key!=='starter')$features[]='Local SEO';$features[]=['starter'=>'SEO expert review & guidance','growth'=>'Assigned SEO expert & monthly review','pro'=>'Dedicated SEO expert & priority coordination'][$key];foreach($features as $feature):?><li><?=e($feature)?></li><?php endforeach;?></ul>
<a class="button <?=$key==='growth'?'':'secondary'?>" data-expert-open="plan" data-plan="<?=$key?>" data-duration="<?=$months?>" href="<?=url('/hire-seo-expert?plan='.$key.'&duration='.$months.'&enquire=1#expert-enquiry')?>">Choose Plan<span class="sr-only"> <?=e($name.' '.$duration)?></span></a></article><?php endforeach;?></div></div><?php endforeach;?>
<p class="small">Monthly equivalents are rounded; the full package price applies. Savings compare with renewing the same 3-month plan over the selected duration. Scope is confirmed in your proposal. Search rankings vary and are not guaranteed.</p>
<div class="expert-copy"><div><h3>SEO expertise that turns insight into action</h3><p>Improve Google visibility &amp; rankings with a strategy built around your website, audience and target locations. Your program connects technical SEO, keyword research, on-page improvements and content planning with regular performance reviews.</p></div><div><h3>What happens after your enquiry?</h3><p>Share your website and goals. Our team reviews your needs, discusses priorities and proposes a plan. Once your program starts, track monthly tasks, ranking progress and SEO reports with your assigned expert.</p></div></div>
</section>
<?php require ROOT.'/public/seo-expert-form.php';?>
<script src="<?=url('/assets/js/seo-expert.js')?>" defer></script>
