<?php $title='SEO tools, business leads & expert support';$description='Grow with SEO Zentro: website audits, keyword tracking, local SEO, business lead research and expert SEO services. Compare plans and start your free workspace.';require ROOT.'/includes/header.php';require ROOT.'/public/zentro-nav.php';?>
<main id="main" class="zentro-home"><section class="container zentro-hero"><div><span class="eyebrow">YOUR NEXT CUSTOMER STARTS WITH A SEARCH</span><h1>Get found.<br>Find opportunities.<br><em>Grow with clarity.</em></h1><p>SEO tools, business research and expert support in one place. Know what to improve, put your plan into action, and track your progress with SEO Zentro.</p><div class="row"><a class="button" href="<?=url('/register')?>">Create your free workspace →</a><a class="button secondary" href="<?=url('/pricing')?>">Explore plans</a></div><p class="small">Free plan available · Clear monthly pricing · Built for businesses and agencies</p></div><img src="<?=url('/assets/images/growth-workspace.svg')?>" width="600" height="520" alt="SEO Zentro workflow: audit your website, discover business opportunities, then measure your progress."></section>
<section class="zentro-band"><div class="container row between"><span>One workspace. A clear next step.</span><strong>Audit → Improve → Measure → Grow</strong></div></section>
<section class="container section-pad" id="services"><div class="section-head"><span class="eyebrow">CHOOSE WHAT YOUR BUSINESS NEEDS</span><h2>Less guesswork.<br>More useful action.</h2><p>Start with a website audit, build your search strategy, or get help from an SEO specialist.</p></div><div class="grid grid-3"><?php foreach([
 ['01','Website audits','Find broken pages, missing metadata and technical issues. Turn findings into a practical task list.','/features','Explore SEO tools'],
 ['02','Rankings & local SEO','Track keywords and review your local presence so you can see where your work is making progress.','/features','See workspace features'],
 ['03','Content & reporting','Organize content ideas, create briefs and share clear reports with your team or clients.','/features','Explore the workspace'],
 ['04','Google Maps leads','Research businesses by category and city. Our team can help with lead research from public listings.','/google-maps-leads','Explore Maps research'],
 ['05','Yelp & Yellow Pages leads','Discover directory listings and available business details for your target market.','/yelp-leads','Explore directory research'],
 ['06','Expert SEO support','Need someone to help implement your strategy? Tell us your goals and request a tailored service quote.','/hire-seo-expert','Talk to an SEO expert']
 ] as [$n,$heading,$copy,$link,$cta]):?><article class="card zentro-service"><span class="zentro-number"><?=e($n)?></span><h3><?=e($heading)?></h3><p><?=e($copy)?></p><a href="<?=url($link)?>"><?=e($cta)?> →</a></article><?php endforeach;?></div></section>
<section class="container section-pad"><div class="zentro-process"><div><span class="eyebrow">SIMPLE FROM DAY ONE</span><h2>Your first step<br>takes a few minutes.</h2><a class="button" href="<?=url('/register')?>">Get started</a></div><ol><li><strong>Create your account</strong><p>Start free and add the website you want to improve.</p></li><li><strong>Find your priorities</strong><p>Run an audit and review the issues that need attention.</p></li><li><strong>Choose your next move</strong><p>Upgrade for more capacity or request expert help.</p></li></ol></div></section>
<?php require ROOT.'/public/pricing-cards.php';?>
<section class="container narrow section-pad"><h2>A few things you might be wondering</h2><details><summary>Can I try SEO Zentro before buying?</summary><p>Yes. Create a free account and explore the limits shown in the Free plan. Upgrade from Billing when you need more capacity.</p></details><details><summary>Are lead research services included in every plan?</summary><p>The plans cover the SEO workspace limits listed above. Business lead research is managed by our team. Contact us to confirm coverage, volume and a separate quote.</p></details><details><summary>How quickly will my site rank?</summary><p>Results depend on your website, competition and the work you implement. SEO Zentro helps you identify and measure improvements; it does not promise positions or a ranking deadline.</p></details></section>
<section class="container section-pad"><div class="zentro-cta"><span class="eyebrow">LET’S BUILD YOUR NEXT STAGE</span><h2>Make your next move a clear one.</h2><p>Start your workspace or talk to us about your business.</p><div class="row"><a class="button" href="<?=url('/register')?>">Start free</a><a class="button secondary" href="<?=url('/contact')?>">Contact SEO Zentro</a></div></div></section></main><?php require ROOT.'/includes/footer.php';?>
