CREATE TABLE IF NOT EXISTS local_seo_audits (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 website_id INT UNSIGNED NOT NULL,
 created_by INT UNSIGNED NULL,
 business_name VARCHAR(190) NOT NULL,
 score TINYINT UNSIGNED NOT NULL,
 scoring_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 snapshot MEDIUMTEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX local_seo_history (website_id,id),
 FOREIGN KEY (website_id) REFERENCES websites(id) ON DELETE CASCADE,
 FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
