CREATE TABLE IF NOT EXISTS chat_widgets (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 public_id CHAR(32) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 business_info TEXT NOT NULL,
 config MEDIUMTEXT NOT NULL,
 allowed_origins TEXT NOT NULL,
 enabled TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(user_id,id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chat_knowledge (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 widget_id INT UNSIGNED NOT NULL,
 question VARCHAR(300) NOT NULL,
 keywords VARCHAR(500) NOT NULL DEFAULT '',
 answer TEXT NOT NULL,
 INDEX(widget_id), FOREIGN KEY(widget_id) REFERENCES chat_widgets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chat_conversations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 widget_id INT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE,
 origin VARCHAR(255) NOT NULL,
 mode ENUM('bot','human','closed') NOT NULL DEFAULT 'bot',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 expires_at DATETIME NOT NULL,
 INDEX(widget_id,updated_at), FOREIGN KEY(widget_id) REFERENCES chat_widgets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chat_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 conversation_id BIGINT UNSIGNED NOT NULL,
 role ENUM('visitor','assistant','agent','system') NOT NULL,
 body TEXT NOT NULL,
 client_id VARCHAR(64) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(conversation_id,client_id), INDEX(conversation_id,id),
 FOREIGN KEY(conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chat_leads (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 widget_id INT UNSIGNED NOT NULL,
 conversation_id BIGINT UNSIGNED NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL DEFAULT '',
 phone VARCHAR(40) NOT NULL DEFAULT '',
 email VARCHAR(190) NOT NULL DEFAULT '',
 service VARCHAR(190) NOT NULL DEFAULT '',
 message TEXT NOT NULL,
 status ENUM('New','Contacted','Qualified','Converted') NOT NULL DEFAULT 'New',
 score TINYINT UNSIGNED NOT NULL DEFAULT 0,
 notes TEXT NOT NULL,
 consent_at DATETIME NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(widget_id,status), FOREIGN KEY(widget_id) REFERENCES chat_widgets(id) ON DELETE CASCADE,
 FOREIGN KEY(conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chat_automation_rules (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 widget_id INT UNSIGNED NOT NULL,
 name VARCHAR(120) NOT NULL,
 keyword VARCHAR(120) NOT NULL DEFAULT '',
 min_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
 target_status ENUM('New','Contacted','Qualified','Converted') NOT NULL DEFAULT 'Qualified',
 enabled TINYINT NOT NULL DEFAULT 1,
 INDEX(widget_id), FOREIGN KEY(widget_id) REFERENCES chat_widgets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
