CREATE TABLE IF NOT EXISTS lead_sources (
 id TINYINT UNSIGNED PRIMARY KEY,
 name VARCHAR(30) NOT NULL UNIQUE,
 collection_mode VARCHAR(40) NOT NULL DEFAULT 'authorized_import',
 enabled TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO lead_sources(id,name) VALUES (1,'IndiaMART'),(2,'TradeIndia');
CREATE TABLE IF NOT EXISTS leads (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 source_id TINYINT UNSIGNED NOT NULL,
 business_name VARCHAR(190) NOT NULL,
 category VARCHAR(190) NOT NULL DEFAULT '',
 city VARCHAR(120) NOT NULL DEFAULT '',
 state VARCHAR(120) NOT NULL DEFAULT '',
 address VARCHAR(500) NOT NULL DEFAULT '',
 website VARCHAR(500) NOT NULL DEFAULT '',
 email VARCHAR(190) NOT NULL DEFAULT '',
 phone VARCHAR(40) NOT NULL DEFAULT '',
 provenance VARCHAR(1000) NOT NULL,
 fingerprint CHAR(64) NOT NULL UNIQUE,
 score TINYINT UNSIGNED NOT NULL DEFAULT 0,
 rating ENUM('Hot','Warm','Normal') NOT NULL DEFAULT 'Normal',
 favorite TINYINT(1) NOT NULL DEFAULT 0,
 demo_slot TINYINT UNSIGNED NULL UNIQUE,
 seo_score TINYINT UNSIGNED NULL,
 website_available TINYINT(1) NULL,
 seo_result LONGTEXT NULL,
 audited_at DATETIME NULL,
 created_by BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (source_id) REFERENCES lead_sources(id),
 CONSTRAINT lead_demo_slot CHECK (demo_slot BETWEEN 1 AND 5),
 INDEX lead_source_date(source_id,created_at),
 INDEX lead_score(score), INDEX lead_location(city,state), INDEX lead_created(created_at),
 INDEX lead_email(email), INDEX lead_phone(phone), INDEX lead_website(website(190))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS lead_searches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 keyword VARCHAR(190) NOT NULL,
 location VARCHAR(190) NOT NULL,
 source_id TINYINT UNSIGNED NULL,
 result_count INT UNSIGNED NOT NULL DEFAULT 0,
 is_public TINYINT(1) NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX lead_search_date(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS lead_notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 lead_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 note TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS lead_tags (
 lead_id BIGINT UNSIGNED NOT NULL,
 tag VARCHAR(60) NOT NULL,
 PRIMARY KEY(lead_id,tag),
 FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS lead_activity (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 lead_id BIGINT UNSIGNED NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(60) NOT NULL,
 details TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
 INDEX lead_activity_date(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
