<?php
if(!BtoBLeads::ready()){echo '<div class="alert">Install lead storage with <code>php cron/migrate-b2b-leads.php</code>.</div>';return;}
[$where,$params,$filters]=BtoBLeads::filters($_GET);
$leadId=(int)BtoBLeads::text($_GET,'id',20);$lead=$leadId?BtoBLeads::get($leadId):null;
$stats=row("SELECT COUNT(*) AS total,COALESCE(SUM(source_id=1),0) AS indiamart,COALESCE(SUM(source_id=2),0) AS tradeindia,COALESCE(SUM(created_at>=NOW()-INTERVAL 7 DAY),0) AS new_leads,COALESCE(SUM(score>=70),0) AS quality,COALESCE(SUM(website<>''),0) AS with_website,COALESCE(SUM(website=''),0) AS without_website FROM leads");
$actionFields=static function(string $operation,int $id=0):void {csrf_field();echo '<input type="hidden" name="operation" value="'.e($operation).'"><input type="hidden" name="id" value="'.$id.'">';};
$leadInput=static function(string $name,string $label,string $value='',bool $required=false):void {echo '<label>'.e($label).'<input name="'.e($name).'" value="'.e($value).'" maxlength="'.(BtoBLeads::FIELDS[$name]??190).'" '.($required?'required':'').'></label>';};
?>
<link rel="stylesheet" href="<?=url('/assets/css/b2b-leads.css')?>">
<div class="page-heading"><div><span class="eyebrow">BUSINESS DISCOVERY</span><h1>B2B Lead Extractor</h1><p>Find and manage authorized IndiaMART and TradeIndia business leads.</p></div><a class="button" href="#lead-editor">Add lead</a></div>
<div class="grid grid-4"><?php foreach(['total'=>'Total Leads','indiamart'=>'IndiaMART Leads','tradeindia'=>'TradeIndia Leads','new_leads'=>'New Leads (7 days)','quality'=>'High-Quality Leads','with_website'=>'Leads With Website','without_website'=>'Leads Without Website'] as $key=>$label):?><div class="card metric"><span class="metric-label"><?=e($label)?></span><strong class="metric-value"><?=e($stats[$key])?></strong></div><?php endforeach;?></div>
<section class="card stack" id="lead-discovery"><h2>Extract leads by keyword and location</h2><p>Find indexed IndiaMART and TradeIndia listings through Google search. Review each listing and its business details before saving. Searches use your configured HasData credits; contact details are only available when published by the business.</p>
<?php if(!Serp::available()):?><div class="alert">Connect HasData under Administration &rarr; Settings to enable live discovery.</div><?php endif;?>
<form data-lead-discover><?php $actionFields('discover');?><div class="form-grid"><label>Keyword<input name="keyword" maxlength="190" placeholder="e.g. Packaging" required></label><label>City / location<input name="location" maxlength="190" placeholder="e.g. Mumbai" required></label><?php select_field('source_id','Source',BtoBLeads::SOURCES);?></div><button class="button" <?=Serp::available()?'':'disabled'?>>Extract leads</button></form><div data-lead-discovery-results aria-live="polite"></div></section>
<div class="card stack"><p><strong>Collection: live search, CSV imports and manual entry.</strong> Every saved record retains its source and provenance. Favorites are shared by administrators.</p><nav class="tabs"><a href="<?=url('/admin/b2b-leads')?>">All leads</a><a href="<?=url('/admin/b2b-leads?source_id=1')?>">IndiaMART Leads</a><a href="<?=url('/admin/b2b-leads?source_id=2')?>">TradeIndia Leads</a></nav>
<form method="get" action="<?=url('/admin/b2b-leads')?>"><div class="form-grid">
<?php foreach(['keyword'=>'Keyword / business name','location'=>'City / state','category'=>'Category'] as $key=>$label)$leadInput($key,$label,$filters[$key]);
select_field('source_id','Source',[''=>'All sources']+BtoBLeads::SOURCES,$filters['source_id']);select_field('rating','Lead score',[''=>'All scores','Hot'=>'Hot (70–100)','Warm'=>'Warm (40–69)','Normal'=>'Normal (0–39)'],$filters['rating']);
foreach(['website','email','phone'] as $key)select_field($key,ucfirst($key),[''=>'Any','yes'=>'Available','no'=>'Not available'],$filters[$key]);
field('from','From date','date',$filters['from'],false);field('to','Through date','date',$filters['to'],false);select_field('favorite','Saved leads',[''=>'All','1'=>'Favorites only'],$filters['favorite']);select_field('duplicates','Duplicate detection',[''=>'All','1'=>'Shared website, email or phone'],$filters['duplicates']);
?></div><div class="row"><button class="button">Search leads</button><a href="<?=url('/admin/b2b-leads')?>">Reset filters</a></div></form></div>
<?php
$total=(int)value('SELECT COUNT(*) FROM leads l WHERE '.$where,$params);$pages=max(1,(int)ceil($total/25));$page=max(1,min($pages,(int)BtoBLeads::text($_GET,'page',10)));$offset=($page-1)*25;
$records=rows('SELECT l.*,s.name AS source FROM leads l JOIN lead_sources s ON s.id=l.source_id WHERE '.$where.' ORDER BY l.id DESC LIMIT 25 OFFSET '.$offset,$params);
if($filters['keyword']!==''||$filters['location']!=='')query('INSERT INTO lead_searches(user_id,keyword,location,source_id,result_count) VALUES (?,?,?,?,?)',[$user['id'],$filters['keyword'],$filters['location'],$filters['source_id']?:null,$total]);
?>
<div class="card stack"><div class="row between"><h2>Lead directory</h2><span><?=e($total)?> matching leads</span></div>
<form id="lead-bulk" data-api="b2b-leads" method="post" action="<?=url('/api/v1/b2b-leads')?>"><?php csrf_field();?><div class="table-wrap"><table><thead><tr><th><input type="checkbox" data-lead-select-all aria-label="Select this page"></th><?php foreach(['Business / category','Location','Contacts','Source','Score','SEO','Saved','Details'] as $heading):?><th><?=e($heading)?></th><?php endforeach;?></tr></thead><tbody>
<?php foreach($records as $r):?><tr><td><input type="checkbox" name="ids[]" value="<?=$r['id']?>" aria-label="Select <?=e($r['business_name'])?>"></td><td><strong><?=e($r['business_name'])?></strong><small class="lead-subtext"><?=e($r['category'])?></small><?php if($r['demo_slot']):?><span class="badge">Public demo #<?=e($r['demo_slot'])?></span><?php endif;?></td><td><?=e(implode(', ',array_filter([$r['city'],$r['state']])))?></td><td><?php if($r['website']):?><a href="<?=e($r['website'])?>" target="_blank" rel="noopener noreferrer">Website ↗</a><?php else:?>No website<?php endif;?><small class="lead-subtext"><?=e($r['email']?:'No public email')?></small><small class="lead-subtext"><?=e($r['phone']?:'No public phone')?></small></td><td><?=e($r['source'])?></td><td><span class="badge"><?=e($r['rating'])?> · <?=e($r['score'])?></span></td><td><?=e($r['seo_score']===null?'Not audited':$r['seo_score'].' / 100')?></td><td><?=$r['favorite']?'★':'—'?></td><td><a href="<?=url('/admin/b2b-leads?id='.$r['id'].'#lead-details')?>">View / edit</a></td></tr><?php endforeach;?></tbody></table></div>
<?php if(!$records)empty_state('No matching leads','Import an authorized CSV list or add a business manually. No sample records are mixed into your leads.');?>
<div class="lead-bulk-actions"><?php select_field('operation','Selected leads',['favorite'=>'Save / favorite','unfavorite'=>'Remove favorite','delete'=>'Delete permanently']);?><label class="lead-check"><input type="checkbox" name="confirm_delete" value="1"> Confirm deletion if selected</label><button class="button">Apply to selected</button></div></form>
<form method="post" action="<?=url('/api/v1/b2b-leads')?>" data-lead-export><?php $actionFields('export');foreach($filters as $key=>$v):?><input type="hidden" name="<?=e($key)?>" value="<?=e($v)?>"><?php endforeach;?><div class="lead-bulk-actions"><?php select_field('format','Export format',['csv'=>'CSV','xlsx'=>'Excel (.xlsx)']);?><label class="lead-check"><input type="checkbox" data-export-selected> Export selected rows only</label><button class="button secondary">Download export</button><small>All filtered leads by default. Maximum 10,000 per export.</small></div></form>
<nav class="row between" aria-label="Lead pagination"><span>Page <?=$page?> of <?=$pages?></span><div class="row"><?php if($page>1):?><a href="<?=url('/admin/b2b-leads?'.http_build_query($filters+['page'=>$page-1]))?>">Previous</a><?php endif;if($page<$pages):?><a href="<?=url('/admin/b2b-leads?'.http_build_query($filters+['page'=>$page+1]))?>">Next</a><?php endif;?></div></nav></div>
<?php if($lead):$seo=$lead['seo_result']?json_decode($lead['seo_result'],true):null;?>
<section class="card stack" id="lead-details"><div class="row between"><h2><?=e($lead['business_name'])?></h2><a href="<?=url('/admin/b2b-leads#lead-editor')?>">Create another lead</a></div><p><?=e($lead['source'])?> · Added <?=e($lead['created_at'])?> · Updated <?=e($lead['updated_at'])?></p><p><strong>Authorization / provenance:</strong> <?=e($lead['provenance'])?></p>
<?php if($lead['website']):?><form data-api="b2b-leads"><?php $actionFields('analyze',$leadId);?><button class="button">Analyze Website</button></form><?php endif;?>
<?php if($seo):?><h3>Website SEO audit · <?=e($lead['seo_score']===null?'Not scored':$lead['seo_score'].' / 100')?></h3><p><?=e($seo['scope']??'')?> Last checked: <?=e($lead['audited_at'])?></p><p><strong><?=e($seo['prospect']??'')?></strong></p><dl class="lead-audit-grid"><?php foreach(['meta_title'=>'Meta title','meta_description'=>'Meta description','h1'=>'H1','sitemap'=>'Sitemap','robots'=>'Robots.txt','ssl'=>'SSL','load_ms'=>'Fetch time (ms)','mobile_viewport'=>'Mobile viewport','http_status'=>'HTTP status','website_availability'=>'Website availability'] as $key=>$label):?><div><dt><?=e($label)?></dt><dd><?=e($seo[$key]??'Unknown')?></dd></div><?php endforeach;?></dl><h3>SEO issues</h3><?php foreach($seo['issues']??[] as $issue):?><div class="alert"><strong><?=e($issue['title'])?> · <?=e($issue['severity'])?></strong><p><?=e($issue['fix'])?></p></div><?php endforeach;?><?php endif;?>
<div class="grid grid-2"><div><h3>Notes</h3><?php foreach(rows('SELECT note,created_at FROM lead_notes WHERE lead_id=? ORDER BY id DESC LIMIT 50',[$leadId]) as $note):?><p><?=nl2br(e($note['note']))?><small class="lead-subtext"><?=e($note['created_at'])?></small></p><?php endforeach;?><form data-api="b2b-leads"><?php $actionFields('note',$leadId);?><label>Add note<textarea name="note" maxlength="5000" required></textarea></label><button class="button">Save note</button></form></div><div><h3>Tags</h3><form data-api="b2b-leads"><?php $actionFields('tags',$leadId);?><label>Comma-separated tags (up to 10)<input name="tags" maxlength="600" value="<?=e(implode(', ',array_column(rows('SELECT tag FROM lead_tags WHERE lead_id=? ORDER BY tag',[$leadId]),'tag')))?>"></label><button class="button">Save tags</button></form><h3>Public preview</h3><p>Only five slots exist across both sources. Editing a lead removes it from public display until approved again.</p><form data-api="b2b-leads"><?php $actionFields('demo',$leadId);select_field('demo_slot','Public demo slot',[''=>'Private','1'=>'Slot 1','2'=>'Slot 2','3'=>'Slot 3','4'=>'Slot 4','5'=>'Slot 5'],$lead['demo_slot']??'');?><label class="lead-check"><input type="checkbox" name="public_authorized" value="1"> I have permission to publish this business’s listed contact information on the homepage.</label><button class="button">Update public preview</button></form></div></div>
<h3>Recent lead activity</h3><?php table(['action'=>'Action','created_at'=>'Date','user_id'=>'Admin'],rows('SELECT action,created_at,user_id FROM lead_activity WHERE lead_id=? ORDER BY id DESC LIMIT 30',[$leadId]));?></section>
<?php endif;?>
<section class="card stack" id="lead-editor"><h2><?=$lead?'Edit lead':'Add an authorized lead'?></h2><form data-api="b2b-leads"><?php $actionFields('save',$leadId);?><div class="form-grid"><?php select_field('source_id','Source',BtoBLeads::SOURCES,$lead['source_id']??'1');foreach(BtoBLeads::FIELDS as $key=>$max)$leadInput($key,ucwords(str_replace('_',' ',$key)),(string)($lead[$key]??''),in_array($key,['business_name','provenance']));?></div><label class="lead-check"><input type="checkbox" name="authorized" value="1" required> I am authorized to store this business data and any listed public business contacts.</label><p>Provenance should identify the permitted source URL, licensed list, or authorization reference. Unknown contacts should be left blank.</p><button class="button">Save lead</button></form></section>
<section class="card stack"><h2>Import authorized CSV leads</h2><p>UTF-8 CSV, maximum 2 MB / 1,000 rows. Existing businesses at the same location are skipped across both sources. Shared contacts are flagged for review; they are never automatically merged. An invalid row rejects the entire upload.</p><p>Supported headers: <code><?=e(implode(', ',array_keys(BtoBLeads::FIELDS)))?></code>. Required: business_name and city or state. Source and provenance are assigned from the form below.</p><form data-api="b2b-leads" enctype="multipart/form-data"><?php $actionFields('import');?><div class="form-grid"><?php select_field('source_id','Source',BtoBLeads::SOURCES);$leadInput('provenance','Authorization / source reference','',true);?><label>CSV file<input type="file" name="csv" accept=".csv,text/csv" required></label></div><label class="lead-check"><input type="checkbox" name="authorized" value="1" required> I have permission to import this list, including its business contact information.</label><button class="button">Import leads</button></form></section>
<details class="card stack"><summary>How lead scores work</summary><p>Website +20, email +20, phone +20, complete name/category/city/state +20, verified website availability +10, SEO opportunity +0–10 (lower audited SEO scores add more points). Hot: 70–100; Warm: 40–69; Normal: 0–39. An unaudited website earns no availability or SEO points. “High-Quality” means Hot by this heuristic, not verified buying intent.</p></details>
<script src="<?=url('/assets/js/b2b-leads.js')?>" defer></script>
