<?php
if(!SeoExpert::ready()){echo '<div class="card"><h2>SEO Expert setup</h2><p>Run <code>php cron/migrate-seo-expert.php</code> to install this module.</p></div>';return;}
$experts=[''=>'Unassigned'];foreach(rows("SELECT id,name FROM users WHERE active=1 AND role IN ('admin','super_admin','team_member') ORDER BY name") as $expert)$experts[$expert['id']]=$expert['name'];
function expert_form(string $operation,int $id): void {echo '<form data-api="seo-expert-admin" method="post" action="'.url('/api/v1/seo-expert-admin').'">';csrf_field();echo '<input type="hidden" name="operation" value="'.e($operation).'"><input type="hidden" name="id" value="'.$id.'">';}
function expert_text(string $key,string $label,string $value='',bool $required=true): void {echo '<label>'.e($label).'<textarea name="'.e($key).'" rows="3" '.($required?'required':'').'>'.e($value).'</textarea></label>';}
function expert_contact(array $lead): void {$digits=preg_replace('/\D/','',$lead['phone']);echo '<div class="expert-actions"><a class="button secondary" href="tel:'.e($lead['phone']).'">Call client</a><a class="button secondary" href="https://wa.me/'.$digits.'" target="_blank" rel="noopener">WhatsApp client</a><a class="button secondary" href="mailto:'.e($lead['email']).'">Email client</a></div>';}
?>
<link rel="stylesheet" href="<?=url('/assets/css/seo-expert.css')?>">
<section class="expert-admin"><div class="page-heading"><div><span class="eyebrow">PREMIUM SEO SERVICES</span><h2>SEO Expert Leads Dashboard</h2><p>A dedicated workspace for enquiries, clients and measurable progress.</p></div><a class="button secondary" href="<?=url('/admin/seo-expert')?>">All enquiries</a></div>
<?php if(isset($_GET['client'])): $clientId=filter_var($_GET['client'],FILTER_VALIDATE_INT);if(!$clientId||$clientId<1)fail('Invalid client.',400);$client=SeoExpert::client($clientId);require ROOT.'/admin/seo-expert-client.php';
elseif(isset($_GET['id'])): $leadId=filter_var($_GET['id'],FILTER_VALIDATE_INT);if(!$leadId||$leadId<1)fail('Invalid enquiry.',400);$lead=SeoExpert::enquiry($leadId);require ROOT.'/admin/seo-expert-lead.php';
else:
$counts=array_fill_keys(SeoExpert::STATUSES,0);foreach(rows('SELECT status,COUNT(*) AS n FROM seo_expert_enquiries GROUP BY status') as $r)$counts[$r['status']]=(int)$r['n'];
$revenue=(int)value("SELECT COALESCE(SUM(CASE WHEN kind='refund' THEN -CAST(amount AS SIGNED) ELSE amount END),0) FROM seo_expert_payments WHERE status='paid'");
$stats=['Total Enquiries'=>array_sum($counts),'New Enquiries'=>$counts['New'],'Contacted'=>$counts['Contacted'],'Audit Requested'=>$counts['Audit'],'Proposal Sent'=>$counts['Proposal'],'Payment Pending'=>$counts['Payment Pending'],'Active Clients'=>$counts['Active'],'Closed Leads'=>$counts['Completed']+$counts['Lost'],'Total Revenue'=>money($revenue)];?>
<div class="expert-stats"><?php foreach($stats as $label=>$number):?><article class="card expert-stat"><span><?=e($label)?></span><strong><?=e($number)?></strong></article><?php endforeach;?></div><p class="small">Audit Requested counts leads in the Audit stage. Closed leads include Completed and Lost. Revenue is received payments less paid refunds.</p>
<div class="expert-charts"><?php
$daily=[];for($i=29;$i>=0;$i--)$daily[date('Y-m-d',strtotime('-'.$i.' days'))]=0;foreach(rows('SELECT DATE(created_at) AS day,COUNT(*) AS n FROM seo_expert_enquiries WHERE created_at>=CURRENT_DATE-INTERVAL 29 DAY GROUP BY DATE(created_at)') as $r)$daily[$r['day']]=(int)$r['n'];SeoExpertManagement::chart('Enquiries by day · Last 30 days',array_reverse($daily,true));
$monthly=[];$income=[];for($i=11;$i>=0;$i--){$key=date('Y-m',strtotime(date('Y-m-01').' -'.$i.' months'));$monthly[$key]=0;$income[$key]=0;}
foreach(rows("SELECT DATE_FORMAT(created_at,'%Y-%m') AS month,COUNT(*) AS n FROM seo_expert_enquiries WHERE created_at>=DATE_FORMAT(CURRENT_DATE-INTERVAL 11 MONTH,'%Y-%m-01') GROUP BY month") as $r)$monthly[$r['month']]=(int)$r['n'];SeoExpertManagement::chart('Enquiries by month · Last 12 months',$monthly);
$plans=['Starter'=>0,'Growth'=>0,'Pro'=>0,'Undecided'=>0];foreach(rows('SELECT plan,COUNT(*) AS n FROM seo_expert_enquiries GROUP BY plan') as $r)$plans[ucfirst($r['plan'])]=(int)$r['n'];SeoExpertManagement::chart('Plan selection',$plans);
$durations=['3 Months'=>0,'6 Months'=>0,'1 Year'=>0];foreach(rows('SELECT duration,COUNT(*) AS n FROM seo_expert_clients GROUP BY duration') as $r)$durations[SeoExpert::DURATIONS[$r['duration']]]=(int)$r['n'];SeoExpertManagement::chart('3 / 6 / 12 month client subscriptions',$durations);SeoExpertManagement::chart('Lead status',$counts);
foreach(rows("SELECT DATE_FORMAT(paid_on,'%Y-%m') AS month,SUM(CASE WHEN kind='refund' THEN -CAST(amount AS SIGNED) ELSE amount END) AS n FROM seo_expert_payments WHERE status='paid' AND paid_on>=DATE_FORMAT(CURRENT_DATE-INTERVAL 11 MONTH,'%Y-%m-01') AND paid_on<=CURRENT_DATE GROUP BY month") as $r)$income[$r['month']]=(int)$r['n'];SeoExpertManagement::chart('Net revenue · Last 12 months',$income,true);
?></div>
<?php [$where,$params,$filters]=SeoExpertManagement::filters($_GET);$total=(int)value('SELECT COUNT(*) FROM seo_expert_enquiries e WHERE '.$where,$params);$page=max(1,min((int)($_GET['page']??1),max(1,(int)ceil($total/25))));$leads=rows('SELECT e.*,c.id AS client_id FROM seo_expert_enquiries e LEFT JOIN seo_expert_clients c ON c.enquiry_id=e.id WHERE '.$where.' ORDER BY e.id DESC LIMIT 25 OFFSET '.(($page-1)*25),$params);?>
<div class="card"><h3>Enquiries &amp; clients</h3><form method="get" class="expert-filters"><?php field('q','Search name, business, email or reference','search',$filters['q'],false);select_field('status','Lead status',[''=>'All statuses']+array_combine(SeoExpert::STATUSES,SeoExpert::STATUSES),$filters['status']);select_field('plan','Plan',[''=>'All plans','undecided'=>'Undecided']+SeoExpert::PLANS,$filters['plan']);select_field('duration','Duration',[''=>'All durations']+SeoExpert::DURATIONS,$filters['duration']);?><button class="button">Filter</button></form>
<div class="table-wrap"><table><thead><tr><th>Enquiry</th><th>Business</th><th>Plan / duration</th><th>Status</th><th>Payment</th><th>Follow-up</th><th>Client</th></tr></thead><tbody><?php foreach($leads as $l):?><tr><td><a href="<?=url('/admin/seo-expert?id='.$l['id'])?>"><?=e($l['full_name'])?></a><br><small><?=e($l['reference'])?></small></td><td><?=e($l['business_name'])?></td><td><?=e(ucfirst($l['plan']).' / '.$l['duration'].' months')?></td><td><?=e($l['status'])?></td><td><?=e($l['payment_status'])?></td><td><?=e($l['follow_up_at']??'Not scheduled')?></td><td><?php if($l['client_id']):?><a href="<?=url('/admin/seo-expert?client='.$l['client_id'])?>">Open profile</a><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$leads)empty_state('No enquiries yet','New SEO enquiries will appear here.');?>
<div class="expert-actions"><span><?=e($total)?> enquiries · Page <?=$page?></span><?php if($page>1):?><a href="<?=url('/admin/seo-expert?'.http_build_query($filters+['page'=>$page-1]))?>">Previous</a><?php endif;if($page*25<$total):?><a href="<?=url('/admin/seo-expert?'.http_build_query($filters+['page'=>$page+1]))?>">Next</a><?php endif;?></div>
<form method="post" action="<?=url('/api/v1/seo-expert-admin')?>"><?php csrf_field();?><input type="hidden" name="operation" value="export"><?php foreach($filters as $key=>$v):?><input type="hidden" name="<?=$key?>" value="<?=e($v)?>"><?php endforeach;?><button class="button secondary">Export filtered leads to CSV</button></form></div>
<?php endif;?></section>
