<?php
if(is_file(ROOT.'/storage/installed.lock'))fail('Installation is locked. Use your existing administrator account.',403);
$checks=['PHP 8.2+'=>version_compare(PHP_VERSION,'8.2','>='),'PDO MySQL'=>extension_loaded('pdo_mysql'),'cURL'=>extension_loaded('curl'),'DOM'=>extension_loaded('dom'),'mbstring'=>extension_loaded('mbstring'),'OpenSSL'=>extension_loaded('openssl'),'Fileinfo'=>extension_loaded('fileinfo'),'Storage writable'=>is_writable(ROOT.'/storage'),'Config writable'=>is_writable(ROOT.'/config')];
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();if(in_array(false,$checks,true))fail('Resolve the failed system checks first.');
 if(!cfg('INSTALL_TOKEN')||cfg('INSTALL_TOKEN')==='replace-with-a-long-random-string'||!hash_equals(cfg('INSTALL_TOKEN'),input('install_token',200)))fail('Set a private INSTALL_TOKEN in server configuration and enter it here.',403);
 $host=required_input('db_host',190);$name=required_input('db_name',64);$dbuser=required_input('db_user',100);$password=input('db_pass',200);$port=(int)input('db_port',5,'3306');if(!preg_match('/^[a-zA-Z0-9_]+$/',$name)||!preg_match('/^[a-zA-Z0-9.-]+$/',$host)||$port<1||$port>65535)fail('Invalid database connection settings.');
 $app=rtrim(required_input('app_url',500),'/');if(!filter_var($app,FILTER_VALIDATE_URL)||!in_array(parse_url($app,PHP_URL_SCHEME),['http','https']))fail('Enter a valid application URL.');$email=strtolower(required_input('admin_email',190));$adminPass=required_input('admin_password',200);if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($adminPass)<12)fail('Use a valid administrator email and a password with at least 12 characters.');
 $lock=fopen(ROOT.'/storage/install.guard','c');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))fail('Installation is already running.');if(is_file(ROOT.'/storage/installed.lock'))fail('Installation is locked.',403);
 $pdo=new PDO('mysql:host='.$host.';port='.$port.';dbname='.$name.';charset=utf8mb4',$dbuser,$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);if($pdo->query('SHOW TABLES')->fetch())fail('Choose an empty database to avoid overwriting existing data.');
 $sql=file_get_contents(ROOT.'/database/database.sql');foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql) as $statement)if(trim($statement)!=='')$pdo->exec($statement);
 foreach(preg_split('/;\s*(?:\r?\n|$)/',file_get_contents(ROOT.'/database/migrations/002-workflows.sql')) as $statement)if(trim($statement)!=='')$pdo->exec($statement);$pdo->exec("INSERT INTO settings(name,value) VALUES ('migration_002','true')");
 $pdo->exec(file_get_contents(ROOT.'/database/migrations/003-recommendations.sql'));$pdo->exec("INSERT INTO settings(name,value) VALUES ('migration_003','true')");
 foreach(preg_split('/;\s*(?:\r?\n|$)/',file_get_contents(ROOT.'/database/migrations/004-services.sql')) as $statement)if(trim($statement)!=='')$pdo->exec($statement);$pdo->exec("INSERT INTO settings(name,value) VALUES ('migration_004','true')");
 $pdo->exec(file_get_contents(ROOT.'/database/migrations/005-credit-recovery.sql'));$pdo->exec("INSERT INTO settings(name,value) VALUES ('migration_005','true')");
 $pdo->exec(file_get_contents(ROOT.'/database/migrations/006-local-seo.sql'));$pdo->exec("INSERT INTO settings(name,value) VALUES ('migration_006','true')");
 $s=$pdo->prepare("INSERT INTO users(name,email,password,role,verified_at) VALUES (?,?,?,'super_admin',NOW())");$s->execute([required_input('admin_name',120),$email,password_hash($adminPass,PASSWORD_DEFAULT)]);$uid=$pdo->lastInsertId();$pdo->exec("INSERT INTO user_roles(user_id,role_id) SELECT ".(int)$uid.",id FROM roles WHERE name='super_admin'");
 $local=['DB_HOST'=>$host,'DB_PORT'=>(string)$port,'DB_NAME'=>$name,'DB_USER'=>$dbuser,'DB_PASS'=>$password,'APP_URL'=>$app,'INSTALL_TOKEN'=>bin2hex(random_bytes(32))];$contents="<?php\nreturn ".var_export($local,true).";\n";if(file_put_contents(ROOT.'/config/local.php',$contents,LOCK_EX)===false)fail('Could not save private configuration.');file_put_contents(ROOT.'/storage/installed.lock',date(DATE_ATOM));flock($lock,LOCK_UN);fclose($lock);$_SESSION['flash']='Installation complete. Sign in with the administrator credentials you chose.';header('Location: '.$app.'/login',true,303);exit;
}
$title='Install SEO AutoPilot';require ROOT.'/includes/header.php';?><main class="container narrow" id="main"><span class="eyebrow">YOUR WORKSPACE STARTS HERE</span><h1>Install SEO AutoPilot.</h1><div class="card"><h3>System checks</h3><?php foreach($checks as $label=>$ok):?><div class="score-row"><span><?=e($label)?></span><span class="badge <?=$ok?'active':'critical'?>"><?=$ok?'Ready':'Needs attention'?></span></div><?php endforeach;?></div><div class="card stack"><p>Create an empty MySQL database first. Set INSTALL_TOKEN in a private config file or environment variable before continuing.</p><form method="post"><?php csrf_field();field('install_token','Private installation token','password');?><h3>Database connection</h3><div class="form-grid"><?php field('db_host','Database host','text','127.0.0.1');field('db_port','Database port','number','3306');field('db_name','Database name','text','seo_autopilot');field('db_user','Database username');field('db_pass','Database password','password','',false);?></div><h3>Application & administrator</h3><?php field('app_url','Application URL','url',cfg('APP_URL'));field('admin_name','Administrator name');field('admin_email','Administrator email','email');field('admin_password','Administrator password (12+ characters)','password');?><button class="button">Install workspace →</button></form></div></main><?php require ROOT.'/includes/footer.php';?>
