<?php $p=$data['profile']; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><style>
@page{margin:35px 35px 45px}body{font-family:DejaVu Sans,sans-serif;font-size:10px;line-height:1.6;color:#294134}h1{font-size:23px;margin:0 0 6px}h2{font-size:15px;margin-top:23px}h3{font-size:12px}p{margin:6px 0}.muted{color:#667468;font-size:9px}.score{padding:16px;background:#edf4e7;font-size:22px;border:1px solid #dce6d4;margin:18px 0}table{width:100%;border-collapse:collapse;table-layout:fixed;margin:10px 0}th,td{border:1px solid #dfe6da;padding:7px;vertical-align:top;word-wrap:break-word}th{background:#eef3e9;text-align:left}tr{page-break-inside:avoid}pre{font-family:DejaVu Sans Mono,monospace;font-size:8px;white-space:pre-wrap;word-wrap:break-word;background:#f4f6f0;padding:12px}.section{page-break-before:always}.check{border-bottom:1px solid #e1e8db;padding:8px 0;page-break-inside:avoid}
</style></head><body>
<h1>Local SEO audit</h1><h2><?=e($p['business_name'])?></h2><p>Audit #<?=(int)$audit['id']?> · <?=e($data['captured_at'])?> UTC · Scoring version <?=(int)$data['version']?></p>
<p class="muted"><?=e($data['source'])?> This is an internal readiness checklist, not a Google score, ranking prediction or independent verification. Unknown fields earn no points. Benchmarks are explained in each check.</p>
<div class="score">Local SEO Score: <?=(int)$data['score']?> / 100</div>
<table><thead><tr><th>Section</th><th>Points earned</th></tr></thead><tbody><?php foreach($data['groups'] as $name=>$group):?><tr><td><?=e($name)?></td><td><?=$group['earned']?> / <?=$group['max']?></td></tr><?php endforeach;?></tbody></table>
<h2>Submitted business details</h2><table><tbody><?php foreach(['business_name'=>'Name','category'=>'Primary category','business_type'=>'Business type','phone'=>'Phone','website'=>'Website','profile_url'=>'Profile link','description'=>'Description','service_area'=>'Service area','rating'=>'Reported rating','review_count'=>'Reported reviews','replied_reviews'=>'Replied reviews','last_review_date'=>'Latest review date','photo_count'=>'Reported photos','directory_source'=>'Directory comparison source'] as $key=>$label):?><tr><th><?=e($label)?></th><td><?=e($p[$key]===null||$p[$key]===''?'Not provided':$p[$key])?></td></tr><?php endforeach;?><tr><th>Public address / area</th><td><?=e(LocalSeo::address($p)?:'Not provided')?></td></tr><tr><th>Services</th><td><?=e(implode(', ',$p['services'])?:'Not provided')?></td></tr></tbody></table>
<h2>NAP comparisons</h2><p class="muted">Only supplied text is compared. Punctuation and case are ignored; phone formatting is removed. Abbreviations, country-code differences and other sources need manual review.</p><table><thead><tr><th>Source</th><th>Name</th><th>Address / service area</th><th>Phone</th></tr></thead><tbody><?php foreach(['website'=>'Website','directory'=>'Directory'] as $source=>$label):?><tr><td><?=$label?></td><?php foreach(['name','address','phone'] as $field):?><td><?=e($p[$source.'_'.$field]?:'Not provided')?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table>
<h2>Opening hours</h2><table><tbody><?php foreach($p['hours'] as $day=>$hours):?><tr><td><?=e($day)?></td><td><?=e($hours['state']==='open'?$hours['opens'].'–'.$hours['closes']:str_replace('_',' ',$hours['state']))?></td></tr><?php endforeach;?></tbody></table>
<h2>Website inputs</h2><table><tbody><?php foreach(['page_title'=>'Page title','meta_description'=>'Meta description','h1'=>'Main heading','mobile_friendly'=>'Mobile usability (self-reported)','indexable'=>'Indexability (self-reported)'] as $key=>$label):?><tr><th><?=e($label)?></th><td><?=e($p[$key]?:'Not provided')?></td></tr><?php endforeach;?></tbody></table><p class="muted">Website content and installed schema were analyzed only from pasted text. No URL was fetched.</p>
<h2>Target keywords</h2><p><?=e(implode(', ',$p['keywords'])?:'Not provided')?></p><h2>Suggested local keyword ideas</h2><p><?=e(implode(', ',$data['keyword_ideas'])?:'Add a category, service and locality to produce ideas.')?></p><p class="muted">Ideas are assembled from your entries. No search-volume, difficulty or rank data is claimed.</p>
<div class="section"><h2>Checks, issues and recommendations</h2><?php foreach($data['checks'] as $check):?><div class="check"><h3><?=e($check['group'].' · '.$check['label'])?></h3><p><?=e($check['status'])?> · <?=$check['earned']?> / <?=$check['max']?> points</p><p><?=e($check['evidence'])?></p><p><?=e($check['recommendation'])?></p></div><?php endforeach;?></div>
<div class="section"><h2>LocalBusiness schema draft</h2><p>Review and publish this JSON-LD only where it accurately describes visible page content. Unknown values are omitted. Google review totals are not copied into review markup. For service-area businesses, the private street address is omitted.</p><p class="muted">This generated draft does not count as installed schema in the audit. Eligibility for Google features is not established by this report.</p><pre><?=e($data['schema'])?></pre></div>
</body></html>
