<?php
$keywords=$s['keywords']??[];$backlinks=$s['backlinks']??[];$tasks=$s['tasks']??[];$audit=$s['audit']??null;$pages=$s['page_summary']??null;
$summary=$s['keyword_summary']??KeywordAnalysis::summarize(array_map(fn($k)=>$k+['position'=>null,'ranking_date'=>null],$keywords));
$completed=count(array_filter($tasks,fn($t)=>($t['status']??'')==='completed'));$openIssues=0;$critical=0;$issueTotal=0;
foreach($s['issue_summary']??[] as $r){$issueTotal+=(int)$r['total'];if($r['status']==='open'){$openIssues+=(int)$r['total'];if(in_array($r['severity'],['critical','high']))$critical+=(int)$r['total'];}}
if(!isset($s['issue_summary'])){foreach($s['issues']??[] as $r){$issueTotal++;if(($r['status']??'open')==='open')$openIssues++;}}
$auditTrend=$s['audit_trend']??[];$healthChange=count($auditTrend)>1?(int)end($auditTrend)['score']-(int)$auditTrend[count($auditTrend)-2]['score']:null;
$domains=count(array_unique(array_column($backlinks,'domain')));$lost=count(array_filter($backlinks,fn($b)=>($b['status']??'')==='lost'));
?>
<article class="report-document performance-report">
<?php require ROOT.'/includes/report-brand.php';?>
<header class="report-cover"><p class="report-kicker"><?=e($s['branding']['agency_name']??'SEO AutoPilot')?> / PERFORMANCE INTELLIGENCE</p><h1>SEO performance<br>report</h1><p class="report-domain"><?=e($s['website']['name']??'Website')?> · <?=e($s['website']['domain']??'')?></p><p class="report-period">Snapshot: <?=e($s['captured_at']??$report['created_at'])?> UTC<br>Audience: <?=e(($s['website']['country']??'Not set').' / '.($s['website']['language']??'Not set'))?></p></header>
<section class="report-section"><span class="report-number">01 / EXECUTIVE SUMMARY</span><h2>Your performance at a glance</h2>
<table class="report-metrics"><tr><td><span>SEO health</span><strong><?=e($audit['score']??'—')?></strong><small><?=$audit?'Internal score / 100':'Run an audit to measure'?></small></td><td><span>Top 10 keywords</span><strong><?=$summary['top10']?></strong><small>Of <?=$summary['total']?> tracked keywords</small></td><td><span>Open SEO issues</span><strong><?=$audit?$openIssues:'—'?></strong><small><?=$critical?> critical / high priority</small></td><td><span>Tasks completed</span><strong><?=$completed?></strong><small>Of <?=count($tasks)?> recorded tasks</small></td></tr></table>
<div class="report-callout"><strong>What this means</strong><p><?php if($audit):?>Your latest internal SEO health score is <?=e($audit['score'])?>/100<?= $healthChange!==null?' ('.($healthChange>0?'+':'').$healthChange.' points versus the preceding audit)':''?>. <?=$openIssues?> issues remain open.<?php else:?>An audit has not been recorded yet. Run an audit to establish technical and on-page health.<?php endif;?> <?=$summary['ranked']?> keywords have a recorded position; <?=$summary['unchecked']?> have not been checked. <?=$summary['improved']?> improved and <?=$summary['declined']?> declined where two ranked observations are available.</p></div>
<p class="report-note">This is a saved snapshot of project records. SEO health is an internal diagnostic score. Traffic, clicks, impressions, conversions and revenue are not measured by the current integrations and are not estimated here.</p></section>
<section class="report-section"><span class="report-number">02 / SEARCH VISIBILITY</span><h2>Keyword performance & analysis</h2>
<table class="report-metrics"><tr><td><span>Average position</span><strong><?=e($summary['average']??'—')?></strong><small>Ranked keywords only</small></td><td><span>Positions 1–3</span><strong><?=$summary['top3']?></strong><small>Leading results</small></td><td><span>Positions 11–20</span><strong><?=$summary['top20']?></strong><small>Near page one</small></td><td><span>Not found</span><strong><?=$summary['missing']?></strong><small>In the checked search range</small></td></tr></table>
<?php $keywordRows=[];foreach($keywords as $k){$p=$k['position']??null;$previous=$k['previous_position']??null;$change=$p!==null&&$previous!==null?(int)$previous-(int)$p:null;$keywordRows[]=['keyword'=>$k['keyword'],'position'=>PerformanceReport::rankLabel($k),'change'=>$change===null?'No comparison':($change>0?'+'.$change:($change===0?'Stable':(string)$change)),'audience'=>($k['country']??'').' / '.($k['language']??'').' / '.($k['device']??''),'date'=>$k['ranking_date']??'Not recorded','source'=>$k['ranking_source']??($k['source']??'Not recorded'),'url'=>$k['ranking_url']??($k['target_url']??''),'next'=>KeywordAnalysis::advice($k),'volume'=>$k['search_volume']??'Not supplied','difficulty'=>$k['difficulty']??'Not supplied'];}
PerformanceReport::table(['keyword'=>'Keyword','position'=>'Position','change'=>'Change','audience'=>'Audience','date'=>'Checked','source'=>'Ranking source'],$keywordRows,'Add keywords and run a ranking check to start tracking search visibility.');?>
<p class="report-note">Positive change means improvement. Changes compare the latest position with the previous recorded position, not necessarily yesterday. HasData checks search up to 100 positions; a missing result is not position zero. Legacy API checks may cover a smaller range.</p>
<h3>Keyword action plan</h3><?php PerformanceReport::table(['keyword'=>'Keyword','url'=>'Ranking / target page','volume'=>'Monthly volume','difficulty'=>'Difficulty','next'=>'Recommended action'],$keywordRows);?>
<h3>90-day ranking history</h3><?php PerformanceReport::table(['label'=>'Observation date','value'=>'Average position','ranked'=>'Ranked keywords'],$s['rank_trend']??[],'At least one ranking observation is needed. Averages exclude keywords without a numeric position.');?>
</section>
<section class="report-section"><span class="report-number">03 / WEBSITE HEALTH</span><h2>Technical, content & page performance</h2>
<?php $health=[];foreach(['technical'=>'Technical SEO','onpage'=>'On-page SEO','content'=>'Content quality','performance'=>'Performance diagnostics','linking'=>'Internal linking'] as $key=>$label)$health[]=['area'=>$label,'score'=>$audit!==null?($audit[$key]??'Not measured').' / 100':'Not measured'];PerformanceReport::table(['area'=>'Area','score'=>'Internal score'],$health);?>
<p class="report-note">Latest audit: <?=e($audit['created_at']??'Not available')?>. Crawl status: <?=e($s['crawl']['status']??'Not recorded')?>. Pages processed: <?=e($s['crawl']['processed']??'Not recorded')?> / <?=e($s['crawl']['max_pages']??'Not recorded')?> page limit. This report describes the crawled sample, not every URL on the internet.</p>
<?php if($pages):?><table class="report-metrics"><tr><td><span>Crawled pages</span><strong><?=e($pages['total'])?></strong></td><td><span>HTTP errors</span><strong><?=e($pages['errors']??0)?></strong></td><td><span>Missing descriptions</span><strong><?=e($pages['missing_descriptions']??0)?></strong></td><td><span>Average response</span><strong><?=e($pages['average_response_ms']??'—')?></strong><small>Milliseconds · crawler request</small></td></tr></table><p class="report-note">Noindex pages: <?=e($pages['noindex']??0)?>. Missing titles: <?=e($pages['missing_titles']??0)?>. Images missing alt text: <?=e($pages['missing_alt']??0)?>. Crawler response time is not a Core Web Vitals or browser load-time measurement.</p><?php endif;?>
<h3>Health over recent audits</h3><?php PerformanceReport::table(['created_at'=>'Audit date','score'=>'SEO health / 100'],$auditTrend,'No audit history saved.');?>
<h3>Pages needing attention</h3><p class="report-note">Up to 50 pages with the lowest scores from the latest audit; summary totals above cover its full crawl.</p><?php PerformanceReport::table(['url'=>'Page','http_status'=>'HTTP','score'=>'Score','load_ms'=>'Response ms','word_count'=>'Words','noindex'=>'Noindex (1=yes)'],$s['pages']??[]);?>
</section>
<section class="report-section"><span class="report-number">04 / FIX PRIORITIES</span><h2>Issues & recommendations</h2><p class="report-note"><?=$issueTotal?> total recorded issues in the latest audit. Showing <?=count($s['issues']??[])?> details, prioritizing open and severe issues (maximum 500).</p>
<?php PerformanceReport::table(['severity'=>'Severity','status'=>'Status','total'=>'Count'],$s['issue_summary']??[]);PerformanceReport::table(['title'=>'Issue','severity'=>'Priority','status'=>'Status','url'=>'Affected page','recommendation'=>'Recommended fix'],$s['issues']??[],'No audit issues were recorded. This may mean an audit has not run yet.');?>
</section>
<section class="report-section"><span class="report-number">05 / LINK PROFILE</span><h2>Backlinks & verification</h2>
<table class="report-metrics"><tr><td><span>Recorded links</span><strong><?=count($backlinks)?></strong></td><td><span>Referring domains</span><strong><?=$domains?></strong></td><td><span>Verified present</span><strong><?=e($s['verified_backlinks']??'—')?></strong></td><td><span>Marked lost</span><strong><?=$lost?></strong></td></tr></table>
<?php $linkRows=[];foreach($backlinks as $b)$linkRows[]=['source'=>$b['source_url']??$b['domain'],'target'=>$b['target_url']??'Not recorded','anchor'=>$b['anchor']??'','follow'=>$b['follow']??'Not recorded','status'=>$b['status'],'verification'=>($b['verification']['state']??'Unverified').' / '.($b['verification']['checked_at']??'Not checked'),'message'=>$b['verification']['message']??'','origin'=>$b['source']??'Not recorded'];PerformanceReport::table(['source'=>'Source page','target'=>'Target page','anchor'=>'Anchor','follow'=>'Attribute','status'=>'Status','verification'=>'Verification'],$linkRows,'Add source URLs to the backlink inventory, then verify them.');?>
<p class="report-note">This is the recorded backlink inventory, not a complete backlink index. Live verification checks public source HTML. Blocked pages remain unverified; links inserted by JavaScript can require manual review. Domain authority and domain rating are not calculated from these checks.</p>
</section>
<section class="report-section"><span class="report-number">06 / RESEARCH & COMPETITORS</span><h2>Search opportunities</h2>
<?php $research=$s['research']??[];if($research):?><p>Latest research: <strong><?=e($research['seed'])?></strong> · <?=e($research['source'].' / '.$research['checked_at'])?></p><?php PerformanceReport::table(['keyword'=>'Keyword or question','type'=>'Origin','search_volume'=>'Monthly volume','difficulty'=>'Difficulty'],$research['ideas']??[]);else:?><p class="report-empty">Run Keyword Research to capture related searches and questions in your next report.</p><?php endif;?>
<h3>Recorded competitors</h3><?php PerformanceReport::table(['domain'=>'Competitor','notes'=>'Research notes'],$s['competitors']??[],'Add competitors to maintain your comparison list.');?>
</section>
<section class="report-section"><span class="report-number">07 / DELIVERY & NEXT STEPS</span><h2>Turn findings into progress</h2><p><?=$completed?> of <?=count($tasks)?> tasks completed<?=count($tasks)?' ('.round($completed/count($tasks)*100).'%)':''?>.</p>
<?php PerformanceReport::table(['title'=>'Task','priority'=>'Priority','status'=>'Status','due_date'=>'Due date'],$tasks,'Create tasks from your audit findings to track implementation.');?>
<ol class="report-next"><li><strong>Fix access and indexing problems.</strong> Review critical and high-priority audit issues before content refinements.</li><li><strong>Improve the most relevant ranking pages.</strong> Use the keyword action plan and current search results to prioritize useful changes.</li><li><strong>Verify links and complete assigned work.</strong> Review unverified or missing backlinks and keep task statuses current.</li><li><strong>Measure again.</strong> Run a fresh audit and ranking checks after changes, then generate a new report for comparison.</li></ol>
<p class="report-note">Report sections reflect data available at creation. Existing reports do not change when new checks run. Missing values mean “not measured” or “not supplied,” never an estimated zero.</p>
</section>
<footer class="report-closing"><strong><?=e($s['branding']['agency_name']??'SEO AutoPilot')?></strong><p><?=e($s['branding']['report_footer']??'SEO diagnostics support decisions. Search engine rankings are not guaranteed.')?></p><small><?=e($report['title'])?> · Report #<?=e($report['id']??'Preview')?></small></footer>
</article>
