<?php
$admin=require_admin();$op=substr($action,6);
if($op==='chat-install'){require_admin(true);LiveChat::migrate();audit_log('admin.chat.installed');json_response(['redirect'=>url('/admin/tools')],'Chat storage installed.');}
if($op==='instagram-service'){
 $data=['name'=>required_input('name',120),'description'=>required_input('description',1000),'enabled'=>enum_input('enabled',['0','1'])==='1','visible'=>enum_input('visible',['0','1'])==='1'];
 try{$data['slug']=DomainDns::validateSlug(required_input('slug',80));}catch(InvalidArgumentException $e){fail($e->getMessage());}
 if($data['slug']===DomainDns::settings()['slug'])fail('This slug is already used by the Domain & DNS Checker.');
 db()->beginTransaction();query('INSERT INTO settings(name,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',['instagram_downloader_service',json_encode($data,JSON_THROW_ON_ERROR)]);audit_log('admin.instagram_service.updated',$data);db()->commit();json_response(['redirect'=>url('/admin/tools')],'Instagram downloader settings saved.');
}
if($op==='domain-dns-service'){
 $data=['name'=>required_input('name',120),'description'=>required_input('description',1000),'enabled'=>enum_input('enabled',['0','1'])==='1','visible'=>enum_input('visible',['0','1'])==='1'];
 try{$data['slug']=DomainDns::validateSlug(required_input('slug',80));}catch(InvalidArgumentException $e){fail($e->getMessage());}
 if($data['slug']===InstagramDownloader::settings()['slug'])fail('This slug is already used by the Instagram downloader.');
 db()->beginTransaction();query('INSERT INTO settings(name,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',['domain_dns_service',json_encode($data,JSON_THROW_ON_ERROR)]);audit_log('admin.domain_dns.updated',$data);db()->commit();json_response(['redirect'=>url('/admin/tools')],'Domain & DNS Checker settings saved.');
}
require ROOT.'/api/admin-extended.php';
if(in_array($op,['user','plan','coupon','settings','page','backup']))require_admin(true);
if($op==='user'){$id=(int)($_POST['id']??0);$role=enum_input('role',['super_admin','admin','team_member','customer']);$active=enum_input('active',['0','1']);if($id===$admin['id'])fail('You cannot change your own administrative access.');if(!row('SELECT id FROM users WHERE id=?',[$id]))fail('User not found.',404);query('UPDATE users SET role=?,active=? WHERE id=?',[$role,(int)$active,$id]);query('DELETE FROM user_roles WHERE user_id=?',[$id]);query('INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE name=?',[$id,$role]);audit_log('admin.user.updated',['id'=>$id,'role'=>$role,'active'=>$active]);json_response();}
if($op==='plan'){$id=(int)($_POST['id']??0);$p=row('SELECT * FROM plans WHERE id=?',[$id]);if(!$p)fail('Plan not found.');$data=['name'=>required_input('name',80)];foreach(['price','websites','keywords','crawl_pages','reports','ai_requests','team_members','white_label'] as $key){$v=input($key,10);if(!preg_match('/^-?\d+$/',$v)||($key!=='reports'&&(int)$v<0)||(int)$v>100000000||($key==='reports'&&(int)$v< -1))fail('Invalid '.$key);$data[$key]=(int)$v;}if($data['crawl_pages']<1||$data['crawl_pages']>25000||$data['white_label']>1)fail('Crawl pages must be 1–25,000 and white label 0 or 1.');if($p['slug']==='free'&&$data['price']!==0)fail('The Free plan must remain free.');query('UPDATE plans SET '.implode(',',array_map(fn($k)=>$k.'=?',array_keys($data))).' WHERE id=?',array_merge(array_values($data),[$id]));audit_log('admin.plan.updated',['id'=>$id]);json_response();}
if($op==='coupon'){$code=strtoupper(required_input('code',60));if(value('SELECT id FROM coupons WHERE code=?',[$code]))fail('This coupon code already exists. Choose a different code.');$type=enum_input('type',['percentage','fixed']);$amount=(int)input('amount',10);$start=input('starts_at',30);$end=input('ends_at',30);if($amount<1||($type==='percentage'&&$amount>100)||!strtotime($start)||!strtotime($end)||strtotime($end)<=strtotime($start))fail('Invalid coupon amount or dates.');$limit=(int)input('usage_limit',10);$own=(int)input('per_user_limit',10);if($limit<1||$own<1)fail('Usage limits must be positive.');query('INSERT INTO coupons(code,type,amount,starts_at,ends_at,usage_limit,per_user_limit) VALUES (?,?,?,?,?,?,?)',[$code,$type,$amount,date('Y-m-d H:i:s',strtotime($start)),date('Y-m-d H:i:s',strtotime($end)),$limit,$own]);audit_log('admin.coupon.created');json_response();}
if($op==='settings'){$data=['site_name'=>required_input('site_name',120),'contact_email'=>input('contact_email',190),'crawl_delay_ms'=>(int)input('crawl_delay_ms',5)];if($data['contact_email']&&!filter_var($data['contact_email'],FILTER_VALIDATE_EMAIL))fail('Invalid contact email.');if($data['crawl_delay_ms']<200||$data['crawl_delay_ms']>5000)fail('Crawl delay must be 200–5000 ms.');foreach(['registration','maintenance','require_verification'] as $key)$data[$key]=enum_input($key,['0','1'])==='1';try{$weights=json_decode(input('score_weights',1000),true,16,JSON_THROW_ON_ERROR);}catch(Throwable){fail('Invalid weights JSON.');}if(!is_array($weights)||array_diff(['technical','onpage','content','performance','linking'],array_keys($weights))||count($weights)!==5||array_sum($weights)!==100)fail('All five score weights must total 100.');foreach($weights as $v)if(!is_int($v)||$v<0)fail('Weights must be non-negative integers.');$data['score_weights']=$weights;foreach($data as $k=>$v)query('INSERT INTO settings(name,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',[$k,json_encode($v)]);audit_log('admin.settings.updated');json_response();}
if($op==='page'){$page=enum_input('page',['terms','privacy','refund-policy','cookie-policy','about','contact']);query('INSERT INTO settings(name,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',['page_'.$page,json_encode(required_input('content',60000))]);audit_log('admin.page.updated',['page'=>$page]);json_response();}
if($op==='service'){$r=row('SELECT * FROM human_service_requests WHERE id=?',[(int)($_POST['id']??0)]);if(!$r)fail('Request not found.',404);$assigned=(int)($_POST['assigned_user']??0);if($assigned&&!value('SELECT id FROM users WHERE id=? AND active=1',[$assigned]))fail('Assigned user not found.');$status=enum_input('status',['new','assigned','in_progress','waiting_for_customer','completed','cancelled']);query('UPDATE human_service_requests SET status=?,assigned_user=? WHERE id=?',[$status,$assigned?:null,$r['id']]);if($assigned){$owner=value('SELECT user_id FROM websites WHERE id=?',[$r['website_id']]);query('INSERT IGNORE INTO team_members(owner_id,user_id,website_id) VALUES (?,?,?)',[$owner,$assigned,$r['website_id']]);notify($assigned,'A human SEO service request has been assigned to you.','/human-services?website_id='.$r['website_id']);}notify((int)$r['user_id'],'Your SEO service request is now '.str_replace('_',' ',$status),'/human-services?website_id='.$r['website_id']);audit_log('admin.service.updated',['id'=>$r['id']]);json_response();}
if($op==='backup'){audit_log('admin.database.exported');header('Content-Type: application/sql');header('Content-Disposition: attachment; filename="seo-backup-'.date('Ymd-His').'.sql"');header('Cache-Control: no-store');echo "SET FOREIGN_KEY_CHECKS=0;\n";foreach(query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) as $table){if(!preg_match('/^[a-z_]+$/',$table))continue;$create=query('SHOW CREATE TABLE `'.$table.'`')->fetch(PDO::FETCH_NUM)[1];echo $create.";\n";$stmt=query('SELECT * FROM `'.$table.'`');while($r=$stmt->fetch(PDO::FETCH_ASSOC)){echo 'INSERT INTO `'.$table.'` (`'.implode('`,`',array_keys($r)).'`) VALUES ('.implode(',',array_map(fn($v)=>$v===null?'NULL':db()->quote((string)$v),array_values($r))).");\n";}}echo "SET FOREIGN_KEY_CHECKS=1;\n";exit;}
fail('Unknown admin action.',404);
