<?php
if($op==='subscription'){require_admin(true);$uid=(int)input('user_id',12);$pid=(int)input('plan_id',12);$end=input('ends_at',30);if(!strtotime($end)||strtotime($end)<=time()||!value('SELECT id FROM users WHERE id=?',[$uid])||!value('SELECT id FROM plans WHERE id=? AND active=1',[$pid]))fail('Use an existing user, active plan and future expiry.');db()->beginTransaction();query('SELECT id FROM users WHERE id=? FOR UPDATE',[$uid]);query("UPDATE subscriptions SET status='expired' WHERE user_id=? AND status='active'",[$uid]);query('INSERT INTO subscriptions(user_id,plan_id,starts_at,ends_at,is_trial) VALUES (?,?,NOW(),?,1)',[$uid,$pid,date('Y-m-d H:i:s',strtotime($end))]);notify($uid,'Your account access has been updated by an administrator.','/billing');audit_log('admin.subscription.granted',['user_id'=>$uid,'plan_id'=>$pid]);db()->commit();json_response();}
if($op==='coupon-toggle'){require_admin(true);query('UPDATE coupons SET active=? WHERE id=?',[enum_input('active',['0','1']),(int)input('id',12)]);audit_log('admin.coupon.status');json_response();}
if($op==='quote'){require_admin();$id=(int)input('id',12);$amount=(int)input('amount',12);if($amount<100||$amount>100000000)fail('Quote must be between 100 and 100,000,000 paise.');$r=row('SELECT * FROM human_service_requests WHERE id=?',[$id]);if(!$r)fail('Request not found.');if(value("SELECT id FROM payments WHERE service_request_id=? AND status IN ('pending','paid')",[$id]))fail('A pending or paid quote cannot be changed.');query('UPDATE human_service_requests SET quoted_amount=? WHERE id=?',[$amount,$id]);notify((int)$r['user_id'],'Your SEO service quote is ready.','/human-services?website_id='.$r['website_id']);audit_log('service.quoted',['id'=>$id,'amount'=>$amount]);json_response();}
if($op==='provider'){
 require_admin(true);$provider=enum_input('provider',['ai','ranking','keyword','backlink','smtp','razorpay']);$maps=['ai'=>['AI_ENDPOINT','AI_API_KEY','AI_MODEL'],'ranking'=>['RANKING_ENDPOINT','RANKING_API_KEY'],'keyword'=>['KEYWORD_ENDPOINT','KEYWORD_API_KEY'],'backlink'=>['BACKLINK_ENDPOINT','BACKLINK_API_KEY'],'smtp'=>['SMTP_HOST','SMTP_USER','SMTP_PASS','SMTP_FROM','SMTP_PORT'],'razorpay'=>['RAZORPAY_KEY','RAZORPAY_SECRET','RAZORPAY_WEBHOOK_SECRET']];
 $endpoint=input('endpoint',1000);$key=input('key',1000);$secret=input('secret',1000);$extra=input('extra',1000);$clear=isset($_POST['clear']);$updates=[];
 if($clear)foreach($maps[$provider] as $k)$updates[$k]='';
 else {if(in_array($provider,['ai','ranking','keyword','backlink'])&&$endpoint!==''){try{$endpoint=SafeHttp::normalize($endpoint);SafeHttp::resolve(parse_url($endpoint,PHP_URL_HOST));}catch(Throwable $e){fail($e->getMessage());}if(!str_starts_with($endpoint,'https://'))fail('Provider endpoints must use HTTPS.');}
  if($provider==='ai')$updates=['AI_ENDPOINT'=>$endpoint,'AI_API_KEY'=>$key,'AI_MODEL'=>$extra];elseif(in_array($provider,['ranking','keyword','backlink']))$updates=[strtoupper($provider).'_ENDPOINT'=>$endpoint,strtoupper($provider).'_API_KEY'=>$key];elseif($provider==='razorpay')$updates=['RAZORPAY_KEY'=>$key,'RAZORPAY_SECRET'=>$secret,'RAZORPAY_WEBHOOK_SECRET'=>$extra];else{if($extra&&!filter_var($extra,FILTER_VALIDATE_EMAIL))fail('SMTP sender must be an email address.');if($endpoint&&!preg_match('/^[a-z0-9.-]+$/i',$endpoint))fail('Invalid SMTP hostname.');$port=(int)input('port',5,'587');if(!in_array($port,[465,587]))fail('Use encrypted SMTP on port 465 or 587.');$updates=['SMTP_HOST'=>$endpoint,'SMTP_USER'=>$key,'SMTP_PASS'=>$secret,'SMTP_FROM'=>$extra,'SMTP_PORT'=>$port];}$updates=array_filter($updates,fn($v)=>$v!=='');
 }
 $path=getenv('SEO_CONFIG_FILE')?:ROOT.'/config/local.php';if(!is_file($path)||!is_writable($path))fail('Private configuration is not writable. Update it through your hosting control panel.',503);$lock=fopen(ROOT.'/storage/config.guard','c');if(!$lock||!flock($lock,LOCK_EX))fail('Cannot lock configuration.');$existing=require $path;$new=array_replace($existing,$updates);if(file_put_contents($path,"<?php\nreturn ".var_export($new,true).";\n",LOCK_EX)===false)fail('Unable to save configuration.');flock($lock,LOCK_UN);fclose($lock);audit_log('admin.provider.updated',['provider'=>$provider,'cleared'=>$clear]);json_response([],'Private provider configuration saved');
}
if($op==='scheduling'){require_admin(true);$data=[];foreach(['trial_days'=>[0,90],'trial_plan_id'=>[1,100000],'grace_days'=>[0,14],'ranking_frequency_hours'=>[1,168]] as $key=>[$min,$max]){$v=(int)input($key,10);if($v<$min||$v>$max)fail('Invalid '.$key);$data[$key]=$v;}if(!value('SELECT id FROM plans WHERE id=? AND active=1',[$data['trial_plan_id']]))fail('Trial plan not found.');foreach($data as $key=>$v)query('INSERT INTO settings(name,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',[$key,json_encode($v)]);audit_log('admin.scheduling.updated');json_response();}
