<?php
if(in_array($action,['page-suggestions','save-page-suggestions'])){$p=row('SELECT * FROM pages WHERE id=? AND website_id=?',[(int)($_POST['id']??0),$w['id']]);if(!$p)fail('Page not found.',404);$generated=$action==='page-suggestions';$content=$generated?AI::chat($w,'Suggest an improved title, meta description, H1, FAQ ideas and internal links for this page. Explain uncertainty. Current metadata: '.json_encode(array_intersect_key($p,array_flip(['url','title','description','h1','h2','word_count'])))):required_input('content',30000);query('INSERT INTO page_recommendations(page_id,website_id,content,source) VALUES (?,?,?,?)',[$p['id'],$w['id'],$content,$generated?'ai':'manual']);json_response(['reply'=>$content],'Recommendations saved for review. Your website has not been changed.');}
if($action==='keyword-bulk'){
 $lines=preg_split('/\r?\n/',required_input('keywords',30000),-1,PREG_SPLIT_NO_EMPTY);$lines=array_values(array_unique(array_map('trim',$lines)));if(count($lines)>1000)fail('Maximum 1,000 keywords per batch.');foreach($lines as $line)if(mb_strlen($line)>190)fail('Each keyword must be at most 190 characters.');
 db()->beginTransaction();query('SELECT id FROM users WHERE id=? FOR UPDATE',[$w['user_id']]);$used=(int)value('SELECT COUNT(*) FROM keywords k JOIN websites w ON w.id=k.website_id WHERE w.user_id=?',[$w['user_id']]);limit_check((int)$w['user_id'],'keywords',$used+count($lines)-1);foreach($lines as $line)query('INSERT IGNORE INTO keywords(website_id,keyword,country,language) VALUES (?,?,?,?)',[$w['id'],$line,$w['country'],$w['language']]);db()->commit();json_response([],'Keyword batch saved');
}
if($action==='competitor-keyword'){owned_website((int)$w['id']);$cid=(int)($_POST['competitor_id']??0);if(!value('SELECT id FROM competitors WHERE id=? AND website_id=?',[$cid,$w['id']]))fail('Competitor not found.');$position=(int)input('position',4);if($position<1||$position>1000)fail('Position must be between 1 and 1000.');query('INSERT INTO competitor_keywords(competitor_id,keyword,position) VALUES (?,?,?)',[$cid,required_input('keyword',190),$position]);json_response();}
if($action==='invite'){owned_website((int)$w['id']);$email=strtolower(required_input('email',190));if(!filter_var($email,FILTER_VALIDATE_EMAIL))fail('Invalid email address.');db()->beginTransaction();query('SELECT id FROM users WHERE id=? FOR UPDATE',[$w['user_id']]);$count=(int)value('SELECT COUNT(DISTINCT user_id) FROM team_members WHERE owner_id=?',[$w['user_id']])+(int)value('SELECT COUNT(*) FROM invitations WHERE owner_id=? AND accepted_at IS NULL AND expires_at>NOW()',[$w['user_id']]);limit_check((int)$w['user_id'],'team_members',$count);$token=bin2hex(random_bytes(32));query('INSERT INTO invitations(owner_id,website_id,email,token_hash,expires_at) VALUES (?,?,?,?,DATE_ADD(NOW(),INTERVAL 7 DAY))',[$w['user_id'],$w['id'],$email,hash('sha256',$token)]);email_queue($email,'You are invited to '.$w['name'],'Register or sign in with this email, then accept your invitation: '.cfg('APP_URL').'/accept-invitation?token='.$token);db()->commit();json_response([],'Invitation queued for email delivery.');}
if($action==='project-settings'){owned_website((int)$w['id']);$tz=input('timezone',60,'UTC');if(!in_array($tz,DateTimeZone::listIdentifiers()))fail('Invalid timezone.');query('UPDATE websites SET name=?,country=?,language=?,search_engine=?,timezone=? WHERE id=?',[required_input('name',120),input('country',80),input('language',40),enum_input('search_engine',['google','bing']),$tz,$w['id']]);foreach(['client_name','client_email'] as $key){$v=input($key,190);if($key==='client_email'&&$v&&!filter_var($v,FILTER_VALIDATE_EMAIL))fail('Invalid client email.');query('INSERT INTO website_settings(website_id,name,value) VALUES (?,?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',[$w['id'],$key,$v]);}query("INSERT INTO website_settings(website_id,name,value) VALUES (?,'monthly_report',?) ON DUPLICATE KEY UPDATE value=VALUES(value)",[$w['id'],isset($_POST['monthly_report'])?'1':'0']);json_response();}
